/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import javax.swing.JOptionPane;
import Negocio.ClsNBalance;
import Entidad.ClsEBalance;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HUILLCA
 */
public class FrmBalance extends javax.swing.JInternalFrame {
double sueldo_empleado;
double alquiler;
double luz;
double agua;
double otro;
double total;
double compras;
double ventas;
double total_final;
    /**
     * Creates new form FrmBalance
     */
    public FrmBalance() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        dfinicio = new datechooser.beans.DateChooserCombo();
        dfin = new datechooser.beans.DateChooserCombo();
        jLabel19 = new javax.swing.JLabel();
        pnlpagos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtempleado = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtalquiler = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txtluz = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        txtagua = new javax.swing.JTextField();
        txtotro = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtotal = new javax.swing.JTextField();
        btncalcularpagos = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pbltotal = new javax.swing.JPanel();
        btncalculartotales = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtcompras = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtpagoservicio = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtventas = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        txtganancias = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gastos y Ganancias Mensuales");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 3, 89));
        jLabel18.setText("FECHA FINAL   :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(3, 3, 89));
        jLabel20.setText("FECHA INICIAL :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jButton14.setBackground(new java.awt.Color(204, 255, 255));
        jButton14.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(3, 3, 89));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px.png"))); // NOI18N
        jButton14.setText("PROCESAR");
        jButton14.setHideActionText(true);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setOpaque(false);
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 80));

        dfinicio.setCalendarBackground(new java.awt.Color(204, 255, 255));
        dfinicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dfinicio.setCalendarPreferredSize(new java.awt.Dimension(441, 270));
        dfinicio.setNothingAllowed(false);
        dfinicio.setLocale(new java.util.Locale("pt", "BR", ""));
        dfinicio.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dfinicioOnCommit(evt);
            }
        });
        jPanel2.add(dfinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 200, 30));

        dfin.setCalendarBackground(new java.awt.Color(204, 255, 255));
        dfin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dfin.setCalendarPreferredSize(new java.awt.Dimension(441, 270));
        dfin.setNothingAllowed(false);
        dfin.setLocale(new java.util.Locale("pt", "BR", ""));
        dfin.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dfinOnCommit(evt);
            }
        });
        jPanel2.add(dfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 650, 100));

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 3, 89));
        jLabel19.setText("SUMATORIA TOTAL");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        pnlpagos.setBackground(new java.awt.Color(255, 255, 255));
        pnlpagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlpagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(3, 3, 89));
        jLabel25.setText("EMPLEADOS  :");
        pnlpagos.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(3, 3, 89));
        jLabel26.setText("ALQUILER   :");
        pnlpagos.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        jLabel27.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(3, 3, 89));
        jLabel27.setText("LUZ        :");
        pnlpagos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(3, 3, 89));
        jLabel28.setText("AGUA       :");
        pnlpagos.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));
        pnlpagos.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 120, 20));

        txtempleado.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtempleado.setForeground(new java.awt.Color(8, 91, 184));
        txtempleado.setText("0.0");
        txtempleado.setBorder(null);
        pnlpagos.add(txtempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, 20));
        pnlpagos.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 20));

        txtalquiler.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtalquiler.setForeground(new java.awt.Color(8, 91, 184));
        txtalquiler.setText("0.0");
        txtalquiler.setBorder(null);
        pnlpagos.add(txtalquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 20));
        pnlpagos.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, 20));

        txtluz.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtluz.setForeground(new java.awt.Color(8, 91, 184));
        txtluz.setText("0.0");
        txtluz.setBorder(null);
        pnlpagos.add(txtluz, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 20));
        pnlpagos.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 120, 20));

        txtagua.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtagua.setForeground(new java.awt.Color(8, 91, 184));
        txtagua.setText("0.0");
        txtagua.setBorder(null);
        pnlpagos.add(txtagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 120, 20));

        txtotro.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtotro.setForeground(new java.awt.Color(8, 91, 184));
        txtotro.setText("0.0");
        txtotro.setBorder(null);
        pnlpagos.add(txtotro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 20));
        pnlpagos.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 20));

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(3, 3, 89));
        jLabel30.setText("OTRO       :");
        pnlpagos.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 30));
        pnlpagos.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 160, 20));

        txtotal.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtotal.setForeground(new java.awt.Color(8, 91, 184));
        txtotal.setBorder(null);
        pnlpagos.add(txtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, 20));

        btncalcularpagos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btncalcularpagos.setForeground(new java.awt.Color(3, 3, 89));
        btncalcularpagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncalcularpagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px_1.png"))); // NOI18N
        btncalcularpagos.setText("CALCULAR");
        btncalcularpagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncalcularpagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncalcularpagos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncalcularpagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncalcularpagosMouseClicked(evt);
            }
        });
        pnlpagos.add(btncalcularpagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 150));

        jLabel35.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(3, 3, 89));
        jLabel35.setText("TOTAL S/.");
        pnlpagos.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 30));

        jPanel1.add(pnlpagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 650, 140));

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(3, 3, 89));
        jLabel31.setText("PAGO EMPLEADOS/OTROS SERVICIOS");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        pbltotal.setBackground(new java.awt.Color(255, 255, 255));
        pbltotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pbltotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncalculartotales.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btncalculartotales.setForeground(new java.awt.Color(3, 3, 89));
        btncalculartotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncalculartotales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px_1.png"))); // NOI18N
        btncalculartotales.setText("CALCULAR");
        btncalculartotales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncalculartotales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncalculartotales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncalculartotales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncalculartotalesMouseClicked(evt);
            }
        });
        pbltotal.add(btncalculartotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));
        pbltotal.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 120, 20));

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(3, 3, 89));
        jLabel32.setText("PAGO SERVICIOS :");
        pbltotal.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 30));

        jLabel34.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(3, 3, 89));
        jLabel34.setText("COMPRAS        :");
        pbltotal.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        txtcompras.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtcompras.setForeground(new java.awt.Color(8, 91, 184));
        txtcompras.setText("0.0");
        txtcompras.setBorder(null);
        pbltotal.add(txtcompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 20));
        pbltotal.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, 20));

        txtpagoservicio.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtpagoservicio.setForeground(new java.awt.Color(8, 91, 184));
        txtpagoservicio.setText("0.0");
        txtpagoservicio.setBorder(null);
        txtpagoservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpagoservicioActionPerformed(evt);
            }
        });
        pbltotal.add(txtpagoservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 20));

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(3, 3, 89));
        jLabel33.setText("VENTAS         :");
        pbltotal.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 30));

        txtventas.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtventas.setForeground(new java.awt.Color(8, 91, 184));
        txtventas.setText("0.0");
        txtventas.setBorder(null);
        txtventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtventasActionPerformed(evt);
            }
        });
        pbltotal.add(txtventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, 20));
        pbltotal.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, 20));

        jLabel29.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(3, 3, 89));
        jLabel29.setText("GANANCIAS S/.");
        pbltotal.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        txtganancias.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtganancias.setForeground(new java.awt.Color(8, 91, 184));
        txtganancias.setBorder(null);
        pbltotal.add(txtganancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 160, 20));
        pbltotal.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 20));

        jPanel1.add(pbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 650, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfinicioOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dfinicioOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dfinicioOnCommit

    private void dfinOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dfinOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dfinOnCommit
String fechainicio;
String fechafinal;
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mtdgenerarsueldo();
        mtdgenerarcompras();
        mtdgenerarventas();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btncalcularpagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcularpagosMouseClicked
        sueldo_empleado=Double.parseDouble(txtempleado.getText());
        alquiler=Double.parseDouble(txtalquiler.getText());
        luz=Double.parseDouble(txtluz.getText());
        agua=Double.parseDouble(txtagua.getText());
        otro=Double.parseDouble(txtotro.getText());
        total=sueldo_empleado+alquiler+luz+agua+otro;
        txtotal.setText(total+"");
        txtpagoservicio.setText(total+"");
    }//GEN-LAST:event_btncalcularpagosMouseClicked

    private void btncalculartotalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalculartotalesMouseClicked
        compras=Double.parseDouble(txtcompras.getText());
        ventas=Double.parseDouble(txtventas.getText());
        total_final=ventas-(compras+total);
        txtganancias.setText(total_final+"");
    }//GEN-LAST:event_btncalculartotalesMouseClicked

    private void txtventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtventasActionPerformed

    private void txtpagoservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpagoservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagoservicioActionPerformed
    void mtdcalcularfecha()
    {
        String fecha=dfinicio.getText();
        String[] fechaDividida = fecha.split("/");
        fechainicio=fechaDividida[2]+"-"+fechaDividida[1]+"-"+fechaDividida[0];
        String fecha1=dfin.getText();
        String[] fechaDividida1 = fecha1.split("/");
        fechafinal=fechaDividida1[2]+"-"+fechaDividida1[1]+"-"+fechaDividida1[0];
        
    }
    void mtdgenerarsueldo()
    {
        mtdcalcularfecha();
        ClsEBalance objEC=new ClsEBalance();
        ClsNBalance objNC=new ClsNBalance();
        objEC.setFecha_inicio(fechainicio);
        objEC.setFecha_final(fechafinal);
        if(!fechainicio.equals("") || !fechafinal.equals(""))
        {
            if(objNC.buscarsueldo(objEC)==true)
            {
                txtempleado.setText(String.valueOf(objEC.getSueldo_empleado()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "no se encuentran empleados con planilla por esas fechas");
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "debe seleccionar una fecha");
        }
    }
    void mtdgenerarcompras()
    {
        mtdcalcularfecha();
        ClsEBalance objEC=new ClsEBalance();
        ClsNBalance objNC=new ClsNBalance();
        objEC.setFecha_inicio(fechainicio);
        objEC.setFecha_final(fechafinal);
        if(!fechainicio.equals("") || !fechafinal.equals(""))
        {
            if(objNC.buscarcompras(objEC)==true)
            {
                txtcompras.setText(String.valueOf(objEC.getCompras()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "no se encuentran compras por esas fechas");
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "debe seleccionar una fecha");
        }
        
    }
    void mtdgenerarventas()
    {
        mtdcalcularfecha();
        ClsEBalance objEC=new ClsEBalance();
        ClsNBalance objNC=new ClsNBalance();
        objEC.setFecha_inicio(fechainicio);
        objEC.setFecha_final(fechafinal);
        if(!fechainicio.equals("") || !fechafinal.equals(""))
        {
            if(objNC.buscarventas(objEC)==true)
            {
                txtventas.setText(String.valueOf(objEC.getVentas()));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "no se encuentran ventas por esas fechas");
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "debe seleccionar una fecha");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncalcularpagos;
    private javax.swing.JLabel btncalculartotales;
    private datechooser.beans.DateChooserCombo dfin;
    private datechooser.beans.DateChooserCombo dfinicio;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JPanel pbltotal;
    private javax.swing.JPanel pnlpagos;
    private javax.swing.JTextField txtagua;
    private javax.swing.JTextField txtalquiler;
    private javax.swing.JTextField txtcompras;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtganancias;
    private javax.swing.JTextField txtluz;
    private javax.swing.JTextField txtotal;
    private javax.swing.JTextField txtotro;
    private javax.swing.JTextField txtpagoservicio;
    private javax.swing.JTextField txtventas;
    // End of variables declaration//GEN-END:variables
}
