/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsECliente;
import Entidad.ClsEproducto;
import Entidad.ClsEventa;
import Entidad.ClsEDetalleventa;
import Negocio.Clsventa;
import Entidad.ClsEcaja;
import Negocio.ClsNcaja;
import Entidad.ClsEIgv;
import Negocio.ClsNigv;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HUILLCA
 */
public class Frmboleta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frmboleta
     */
    String cuenta_serie;
    int op;
    int tipodocumento=0;
    int idp;
    double tpagar;
    double porcentaje;
    int cat;
    int productoid;
    double preci;
    double importe = 0;
    double igv, subtotal, total;
    String idcliente="";
    public static int idvendedor=0;
    DefaultTableModel modelo=new DefaultTableModel();
    public Frmboleta() {
        initComponents();
        generarserie();
        generarfecha();
        bloquear();
        lblidempleado.setText(idvendedor+"  --- "+idcliente);        
    }
    void generarserie(){
        int nuevoCodigo;
        int codigoAnterior = 0;
        ClsEventa objEC=new ClsEventa();
        Clsventa objNC=new Clsventa();
        String serie=objNC.NroSerie();
        if(serie==null)
        {
            txtserie.setText("100001");
        }
        else
        {
            codigoAnterior=Integer.parseInt(serie);
            nuevoCodigo=codigoAnterior + 1;
            txtserie.setText(String.valueOf(nuevoCodigo));
        }
    }
    void generarfecha()
    {
        Date date=new Date();
        DateFormat fechaHora=new SimpleDateFormat("yyyy-MM-dd ");
        txtfecha.setText(fechaHora.format(date).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlcliente = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lbldocumento = new javax.swing.JLabel();
        btnbcliente = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtdni = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        pnlproducto = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtbuscarproducto = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rSMTextFull12 = new rojeru_san.RSMTextFull();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtprecio = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtagregarproducto = new javax.swing.JLabel();
        txtstock = new javax.swing.JLabel();
        txtnombrep = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnboleta = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtserie = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdetalle = new javax.swing.JTable();
        pnlventa = new javax.swing.JPanel();
        lbltotal = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        lbligv = new javax.swing.JLabel();
        btnquitar = new javax.swing.JLabel();
        btnvender = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JLabel();
        spsubtotal = new javax.swing.JSeparator();
        spigv = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txtsubtotal = new javax.swing.JLabel();
        txtigv = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        cbotipo = new javax.swing.JComboBox<>();
        lblidempleado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(204, 255, 255));
        jButton10.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(3, 3, 89));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        jButton10.setText("Cancelar");
        jButton10.setHideActionText(true);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 150, 80));

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPROBANTE DE VENTA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 330, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 50));

        pnlcliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlcliente.setLayout(null);

        lblnombre.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(3, 3, 89));
        lblnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombre.setText("NOMBRE :");
        lblnombre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblnombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlcliente.add(lblnombre);
        lblnombre.setBounds(0, 60, 170, 23);

        lbldocumento.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbldocumento.setForeground(new java.awt.Color(3, 3, 89));
        lbldocumento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldocumento.setText("RUC :");
        lbldocumento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbldocumento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlcliente.add(lbldocumento);
        lbldocumento.setBounds(60, 20, 80, 23);

        btnbcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_35px.png"))); // NOI18N
        btnbcliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbclienteMouseClicked(evt);
            }
        });
        pnlcliente.add(btnbcliente);
        btnbcliente.setBounds(370, 10, 50, 50);

        txtnombre.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(0, 0, 51));
        txtnombre.setBorder(null);
        pnlcliente.add(txtnombre);
        txtnombre.setBounds(140, 50, 220, 30);
        pnlcliente.add(jSeparator1);
        jSeparator1.setBounds(140, 80, 220, 10);

        txtdni.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdni.setForeground(new java.awt.Color(0, 0, 51));
        txtdni.setBorder(null);
        pnlcliente.add(txtdni);
        txtdni.setBounds(140, 10, 220, 30);
        pnlcliente.add(jSeparator2);
        jSeparator2.setBounds(140, 40, 220, 10);

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(3, 3, 89));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DIRECION :");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlcliente.add(jLabel17);
        jLabel17.setBounds(10, 110, 130, 23);

        txtdireccion.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 51));
        txtdireccion.setBorder(null);
        pnlcliente.add(txtdireccion);
        txtdireccion.setBounds(140, 100, 220, 30);
        pnlcliente.add(jSeparator10);
        jSeparator10.setBounds(140, 130, 220, 10);

        jPanel1.add(pnlcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 430, 170));

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 3, 89));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DATOS DEL PRODUCTO");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 200, 23));

        pnlproducto.setBackground(new java.awt.Color(255, 255, 255));
        pnlproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlproducto.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 3, 89));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CANTIDAD:");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlproducto.add(jLabel19);
        jLabel19.setBounds(230, 60, 110, 30);

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(3, 3, 89));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("CODIGO :");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlproducto.add(jLabel21);
        jLabel21.setBounds(10, 20, 110, 23);

        txtbuscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_35px.png"))); // NOI18N
        txtbuscarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbuscarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuscarproductoMouseClicked(evt);
            }
        });
        pnlproducto.add(txtbuscarproducto);
        txtbuscarproducto.setBounds(290, 0, 50, 50);
        pnlproducto.add(txtcantidad);
        txtcantidad.setBounds(340, 60, 60, 30);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(3, 3, 89));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CANTIDAD :");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel20);
        jLabel20.setBounds(10, 100, 120, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_35px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel9);
        jLabel9.setBounds(360, 10, 40, 40);

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(3, 3, 89));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("NOMBRE :");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel30);
        jLabel30.setBounds(30, 20, 100, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_50px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel10);
        jLabel10.setBounds(360, 50, 50, 50);

        rSMTextFull12.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        rSMTextFull12.setPlaceholder("00000000");
        rSMTextFull12.setSoloNumeros(true);
        jPanel7.add(rSMTextFull12);
        rSMTextFull12.setBounds(130, 10, 217, 33);
        jPanel7.add(jSpinner2);
        jSpinner2.setBounds(130, 90, 80, 30);

        pnlproducto.add(jPanel7);
        jPanel7.setBounds(0, 0, 0, 0);

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(3, 3, 89));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("STOCK :");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlproducto.add(jLabel32);
        jLabel32.setBounds(20, 60, 100, 30);

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(3, 3, 89));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("PRECIO :");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlproducto.add(jLabel33);
        jLabel33.setBounds(10, 130, 110, 30);

        txtcodigo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(0, 0, 51));
        txtcodigo.setBorder(null);
        pnlproducto.add(txtcodigo);
        txtcodigo.setBounds(110, 10, 160, 30);
        pnlproducto.add(jSeparator3);
        jSeparator3.setBounds(110, 40, 160, 10);
        pnlproducto.add(jSeparator4);
        jSeparator4.setBounds(120, 90, 100, 10);
        pnlproducto.add(jSeparator5);
        jSeparator5.setBounds(120, 130, 250, 10);
        pnlproducto.add(jSeparator6);
        jSeparator6.setBounds(130, 130, 260, 10);

        txtprecio.setBorder(null);
        pnlproducto.add(txtprecio);
        txtprecio.setBounds(120, 140, 80, 20);

        jLabel35.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(3, 3, 89));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("NOMBRE :");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlproducto.add(jLabel35);
        jLabel35.setBounds(0, 100, 130, 30);

        txtagregarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_50px.png"))); // NOI18N
        txtagregarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtagregarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtagregarproductoMouseClicked(evt);
            }
        });
        pnlproducto.add(txtagregarproducto);
        txtagregarproducto.setBounds(350, 0, 50, 50);

        txtstock.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtstock.setForeground(new java.awt.Color(0, 0, 51));
        pnlproducto.add(txtstock);
        txtstock.setBounds(120, 60, 90, 30);

        txtnombrep.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtnombrep.setForeground(new java.awt.Color(0, 0, 51));
        pnlproducto.add(txtnombrep);
        txtnombrep.setBounds(120, 100, 260, 30);

        jPanel1.add(pnlproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 80, 410, 170));

        jLabel22.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(3, 3, 89));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("DATOS VENTA");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 23));

        btnboleta.setBackground(new java.awt.Color(255, 255, 255));
        btnboleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnboleta.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(3, 3, 89));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("N°SERIE:");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnboleta.add(jLabel23);
        jLabel23.setBounds(0, 10, 100, 23);

        jLabel24.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(3, 3, 89));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("FECHA :");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnboleta.add(jLabel24);
        jLabel24.setBounds(0, 50, 100, 23);

        txtserie.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtserie.setForeground(new java.awt.Color(0, 0, 51));
        btnboleta.add(txtserie);
        txtserie.setBounds(110, 10, 100, 30);

        txtfecha.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(0, 0, 51));
        btnboleta.add(txtfecha);
        txtfecha.setBounds(100, 50, 140, 30);

        jPanel1.add(btnboleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 100));

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(3, 3, 89));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("DATOS DEL CLIENTE");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, 23));

        jButton11.setBackground(new java.awt.Color(204, 255, 255));
        jButton11.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(3, 3, 89));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/activar_50px.png"))); // NOI18N
        jButton11.setText("Activar");
        jButton11.setHideActionText(true);
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 80));

        tbdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "PRODUCTO", "CANTIDAD", "PRECIO U", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbdetalle);
        if (tbdetalle.getColumnModel().getColumnCount() > 0) {
            tbdetalle.getColumnModel().getColumn(0).setMinWidth(80);
            tbdetalle.getColumnModel().getColumn(0).setMaxWidth(80);
            tbdetalle.getColumnModel().getColumn(1).setMinWidth(120);
            tbdetalle.getColumnModel().getColumn(1).setMaxWidth(120);
            tbdetalle.getColumnModel().getColumn(2).setMinWidth(400);
            tbdetalle.getColumnModel().getColumn(2).setMaxWidth(400);
            tbdetalle.getColumnModel().getColumn(3).setMinWidth(100);
            tbdetalle.getColumnModel().getColumn(3).setMaxWidth(100);
            tbdetalle.getColumnModel().getColumn(4).setMinWidth(100);
            tbdetalle.getColumnModel().getColumn(4).setMaxWidth(100);
            tbdetalle.getColumnModel().getColumn(5).setMinWidth(100);
            tbdetalle.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 900, 270));

        pnlventa.setBackground(new java.awt.Color(255, 255, 255));
        pnlventa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlventa.setLayout(null);

        lbltotal.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(3, 3, 89));
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltotal.setText("TOTAL :");
        lbltotal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbltotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlventa.add(lbltotal);
        lbltotal.setBounds(30, 100, 110, 23);

        lblsubtotal.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lblsubtotal.setForeground(new java.awt.Color(3, 3, 89));
        lblsubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsubtotal.setText("SUBTOTAL :");
        lblsubtotal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblsubtotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlventa.add(lblsubtotal);
        lblsubtotal.setBounds(10, 20, 120, 23);

        lbligv.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbligv.setForeground(new java.awt.Color(3, 3, 89));
        lbligv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbligv.setText("IGV :");
        lbligv.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbligv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbligv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbligvMouseClicked(evt);
            }
        });
        pnlventa.add(lbligv);
        lbligv.setBounds(50, 60, 90, 23);

        btnquitar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnquitar.setForeground(new java.awt.Color(3, 3, 89));
        btnquitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        btnquitar.setText("QUITAR");
        btnquitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnquitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnquitar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnquitarMouseClicked(evt);
            }
        });
        pnlventa.add(btnquitar);
        btnquitar.setBounds(210, 170, 100, 80);

        btnvender.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnvender.setForeground(new java.awt.Color(3, 3, 89));
        btnvender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnvender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/vender_50px.png"))); // NOI18N
        btnvender.setText("VENDER");
        btnvender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvenderMouseClicked(evt);
            }
        });
        pnlventa.add(btnvender);
        btnvender.setBounds(10, 170, 100, 80);

        btnimprimir.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnimprimir.setForeground(new java.awt.Color(3, 3, 89));
        btnimprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir_50px_1.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnimprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnimprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnimprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnimprimirMouseClicked(evt);
            }
        });
        pnlventa.add(btnimprimir);
        btnimprimir.setBounds(110, 170, 100, 80);
        pnlventa.add(spsubtotal);
        spsubtotal.setBounds(140, 40, 140, 10);
        pnlventa.add(spigv);
        spigv.setBounds(140, 80, 140, 10);
        pnlventa.add(jSeparator9);
        jSeparator9.setBounds(140, 120, 140, 10);

        txtsubtotal.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtsubtotal.setForeground(new java.awt.Color(0, 0, 51));
        pnlventa.add(txtsubtotal);
        txtsubtotal.setBounds(140, 10, 140, 30);

        txtigv.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtigv.setForeground(new java.awt.Color(0, 0, 51));
        pnlventa.add(txtigv);
        txtigv.setBounds(140, 50, 140, 30);

        txttotal.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txttotal.setForeground(new java.awt.Color(0, 0, 51));
        pnlventa.add(txttotal);
        txttotal.setBounds(140, 90, 140, 30);

        jPanel1.add(pnlventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 330, 280));

        cbotipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));
        cbotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipoActionPerformed(evt);
            }
        });
        jPanel1.add(cbotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 40));
        jPanel1.add(lblidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        ClsEcaja objEC=new ClsEcaja();
        ClsNcaja objNC=new ClsNcaja();
        objEC.setEstado_caja("1");
        objEC.setFecha(txtfecha.getText());
        if(objNC.VerificarEstadocaja(objEC)==true)
        {
           desbloquear();
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Debe iniciar en caja para generar una boleta");
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

     void bloquear(){
        for(Component a: pnlcliente.getComponents())
        {
            a.setEnabled(false);
        }
        for(Component b: pnlproducto.getComponents())
        {
            b.setEnabled(false);
        }
        for(Component c: pnlventa.getComponents())
        {
            c.setEnabled(false);
        }
    }
    void desbloquear(){
        for(Component a: pnlcliente.getComponents())
        {
            a.setEnabled(true);
        }
        for(Component b: pnlproducto.getComponents())
        {
            b.setEnabled(true);
        }
        for(Component c: pnlventa.getComponents())
        {
            c.setEnabled(true);
        }
    }
    
    private void btnbclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbclienteMouseClicked
        int r;
        ClsECliente objEC=new ClsECliente();
        Clsventa objNC=new Clsventa();
        objEC.setDni(txtdni.getText());
        if(!txtdni.getText().equals(""))
        {
            if(objNC.Verificardni(objEC)==true)
            {
                txtnombre.setText(objEC.getNombre());
                txtdireccion.setText(objEC.getDireccion());
                idcliente=String.valueOf(objEC.getId());
                pnlproducto.setEnabled(true);
                txtcodigo.requestFocus();
                 lblidempleado.setText(idvendedor+"  --- "+idcliente);
                
            }
            else
            {
                r=JOptionPane.showConfirmDialog(null, "El Cliente no se encuentra registrado \n Desea registrarlo?");
                if(r==0)
                {
                    FrmAgregarCliente frm=new FrmAgregarCliente();
                    FrmMenuPrincipal.DpanEscritorio.add(frm);
                    frm.setVisible(true);
                }
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "debe ingresar un usuario");
        }

        
    }//GEN-LAST:event_btnbclienteMouseClicked
int item=0;
    private void txtbuscarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarproductoMouseClicked
        int r;
        ClsEproducto objEC=new ClsEproducto();
        Clsventa objNC=new Clsventa();
        objEC.setCodigo(txtcodigo.getText());
        int valor=(Integer) txtcantidad.getValue();
        if(!txtcodigo.getText().equals(""))
        {
            if(objNC.Verificarproducto(objEC)==true)
            {
                txtnombrep.setText(objEC.getNombre());
                txtstock.setText(String.valueOf(objEC.getStock()));
                txtprecio.setText(String.valueOf(objEC.getPrecio_venta()));  
                productoid=objEC.getId_producto();
                pnlproducto.setEnabled(true);
                txtcodigo.requestFocus();
            }
            else
            {
                r=JOptionPane.showConfirmDialog(null, "El producto no se encuentra registrado \n ¿Desea mostrar lista de productos?");
                if(r==0)
                {
                    FrmListarProductos frm=new FrmListarProductos();
                    FrmMenuPrincipal.DpanEscritorio.add(frm);
                    frm.setVisible(true);
                }
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(null, "debe ingresar un producto");
        }
    }//GEN-LAST:event_txtbuscarproductoMouseClicked

    private void btnquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitarMouseClicked
        if(this.tbdetalle.getSelectedRow()==-1){
        JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila de la tabla.");  
        }
        else{
            int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminar fila seleccionada", "Mensaje del Sistema.", JOptionPane.YES_NO_OPTION);
            if(showConfirmDialog == 0){
                int sel = this.tbdetalle.getSelectedRow();
                modelo.removeRow(sel);
                calcularTotales();
            }
            else{
            }
        }
    }//GEN-LAST:event_btnquitarMouseClicked

    private void txtagregarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtagregarproductoMouseClicked
        mtdagregarproducto();
    }//GEN-LAST:event_txtagregarproductoMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        mtdlimpiar();
        bloquear();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnvenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvenderMouseClicked
        mtdgenerarventa();
        guardardetalle();
    }//GEN-LAST:event_btnvenderMouseClicked

    private void cbotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipoActionPerformed
        if(cbotipo.getSelectedItem().equals("Boleta"))
        {
            lblnombre.setText("NOMBRE :");
            lbldocumento.setText("DNI :");
            tipodocumento=0;
            spigv.setVisible(false);
            spsubtotal.setVisible(false);
            lbligv.setVisible(false);
            lblsubtotal.setVisible(false);
            txtsubtotal.setVisible(false);
            txtigv.setVisible(false);
            op=0;
            
        }
        if(cbotipo.getSelectedItem().equals("Factura"))
        {
            lblnombre.setText("R. SOCIAL:");
            lbldocumento.setText("RUC :");
            tipodocumento=1;
            spigv.setVisible(true);
            spsubtotal.setVisible(true);
            lbligv.setVisible(true);
            lblsubtotal.setVisible(true);
            txtsubtotal.setVisible(true);
            txtigv.setVisible(true);
            op=1;
        }
        
        
    }//GEN-LAST:event_cbotipoActionPerformed

    private void lbligvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbligvMouseClicked
        ClsEventa objECV=new ClsEventa();
        Clsventa objNC=new Clsventa();
        objECV.setIdvendedor(idvendedor);
        if(objNC.Mtdmostartipo(objECV)==true)
        {
            String cantidad= JOptionPane.showInputDialog("Ingrese la nueva cantidad de IGV");
            double cantidad1=Double.parseDouble(cantidad);
            ClsEIgv objEC=new ClsEIgv();
            ClsNigv objNCV=new ClsNigv();
            objEC.setId(1);
            objEC.setCantidad(cantidad1);
            if(objNCV.mtdmodificarigv(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "IGV modificado correctamente");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error al momento de editar IGV");
            }
        }else
        {
            
        }
        
    }//GEN-LAST:event_lbligvMouseClicked

    private void btnimprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnimprimirMouseClicked
        if(op==1)
        {
            //factura
             mtdgenerarfactura();
        }
        else if(op==0)
        {
            //boleta
            mtdgenerarboleta();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccionar una tipo de comprobante de pago");
        }
    }//GEN-LAST:event_btnimprimirMouseClicked
    void mtdagregarproducto()
    {
        double total;
        ClsEproducto objEC=new ClsEproducto();
        modelo=(DefaultTableModel)tbdetalle.getModel();
        String nomp=txtnombrep.getText();
        double precio=Double.parseDouble(txtprecio.getText());
        int cant=Integer.parseInt(txtcantidad.getValue().toString());
        int stock=Integer.parseInt(txtstock.getText());
        total=cant*precio;
        ArrayList lista=new ArrayList();
        if(cant<stock && stock>0 && cant>0)
        {
            int cantidadnueva=stock-cant;
            item=item+1;
            lista.add(item);
            lista.add(productoid);
            lista.add(nomp);
            lista.add(cant);
            lista.add(precio);
            lista.add(total);
            Object[] ob=new Object[6];
            ob[0]=lista.get(0);
            ob[1]=lista.get(1);
            ob[2]=lista.get(2);
            ob[3]=lista.get(3);
            ob[4]=lista.get(4);
            ob[5]=lista.get(5);
            modelo.addRow(ob);
            tbdetalle.setModel(modelo);
            calculartotal();
            calcularTotales();
        }   
        else
        {
            JOptionPane.showMessageDialog(null, "Stock no disponible ");
        }
    }
    void calculartotal()
    {
        tpagar=0;
        for(int i=0;i<tbdetalle.getRowCount();i++)
        {
            cat=Integer.parseInt(tbdetalle.getValueAt(i, 3).toString());
            preci=Double.parseDouble(tbdetalle.getValueAt(i, 4).toString());
            tpagar=tpagar+(cat*preci);
        }
        txtsubtotal.setText(""+tpagar);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnbcliente;
    private javax.swing.JPanel btnboleta;
    private javax.swing.JLabel btnimprimir;
    private javax.swing.JLabel btnquitar;
    private javax.swing.JLabel btnvender;
    private javax.swing.JComboBox<String> cbotipo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JLabel lblidempleado;
    private javax.swing.JLabel lbligv;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel pnlcliente;
    private javax.swing.JPanel pnlproducto;
    private javax.swing.JPanel pnlventa;
    private rojeru_san.RSMTextFull rSMTextFull12;
    private javax.swing.JSeparator spigv;
    private javax.swing.JSeparator spsubtotal;
    private javax.swing.JTable tbdetalle;
    private javax.swing.JLabel txtagregarproducto;
    private javax.swing.JLabel txtbuscarproducto;
    private javax.swing.JSpinner txtcantidad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txtigv;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JLabel txtnombrep;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JLabel txtserie;
    private javax.swing.JLabel txtstock;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables

    private void calcularTotales() {
        mtdcargarporcentaje();
        try {
            int i;
            subtotal = 0;
            igv = 0;
            total = 0;
            int filas = modelo.getRowCount();
            for (i = 0; i < filas; i++) {
                total += Double.parseDouble(tbdetalle.getValueAt(i, 5).toString());
            }
            igv = total * (porcentaje/100);
            subtotal = total - igv;
            txtigv.setText(String.format("%.2f", igv));
            txtsubtotal.setText(String.format("%.2f", subtotal));
            txttotal.setText(String.valueOf(Math.round(total * 10.00) / 10.00));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void mtdlimpiar() {
        txtdni.setText("");
        txtsubtotal.setText("");
        txtnombre.setText("");
        txtcodigo.setText("");
        txtdireccion.setText("");
        txtsubtotal.setText("");
        btnimprimir.setEnabled(true);
        btnquitar.setEnabled(true);
        btnvender.setEnabled(true);
        txtbuscarproducto.setText("");
        txtagregarproducto.setText("");
        txtsubtotal.setText("");
        txtigv.setText("");
        txttotal.setText("");
        txtprecio.setText("");
        txtnombrep.setText("");
        txtstock.setText("");
        int filas = tbdetalle.getRowCount();
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) tbdetalle.getModel();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }

    private void mtdgenerarventa() {
        Date date=new Date();
        DateFormat fechaHora=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        ClsEventa objECV=new ClsEventa();
        Clsventa objNC=new Clsventa();
        String tipoventa=String.valueOf(cbotipo.getSelectedItem());
        objECV.setIdvendedor(idvendedor);
        objECV.setIdcliente(Integer.parseInt(idcliente));
        objECV.setSerie(txtserie.getText());
        cuenta_serie=txtserie.getText();
        objECV.setFecha(txtfecha.getText());
        objECV.setMonto(Double.parseDouble(txttotal.getText()));
        objECV.setEstado("ACTIVO");
        objECV.setTipo(tipoventa);
        if(objNC.MtdGuardarventas(objECV)==true)
        {
            
            JOptionPane.showMessageDialog(null, "Venta realizada con exito");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error de datos genrar ventas");
        }
    }

    private void guardardetalle()
    {
        ClsEDetalleventa objECVV=new ClsEDetalleventa();
        Clsventa objNCV=new Clsventa();
        String idv=objNCV.idventas();
        int idve=Integer.parseInt(idv);
        for(int i=0;i<tbdetalle.getRowCount();i++)
        {
            int idp=Integer.parseInt(tbdetalle.getValueAt(i,1).toString());
            int cant=Integer.parseInt(tbdetalle.getValueAt(i,3).toString());
            double pre=Double.parseDouble(tbdetalle.getValueAt(i, 4).toString());
            objECVV.setIdventas(idve);
            objECVV.setIdproducto(idp);
            objECVV.setCantidad(cant);
            objECVV.setPreventa(pre);
            if(objNCV.MtdGuardardetalle(objECVV)==true)
            {
                JOptionPane.showMessageDialog(null, "Detalle guardado correctamente"); 
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error guardar detalle");
            }
        }
        mtdactualizarstock();
        mtdlimpiar();
        generarserie();
    }
    private void mtdactualizarstock() {
        for(int i=0;i<modelo.getRowCount();i++)
        {
            ClsEproducto objEC=new ClsEproducto();
            idp=Integer.parseInt(tbdetalle.getValueAt(i, 1).toString());
            cat=Integer.parseInt(tbdetalle.getValueAt(i, 3).toString());
            Clsventa objNC=new Clsventa();
            objEC.setId_producto(idp);
            int sa=(Integer.parseInt(txtstock.getText()))-cat;
            objEC.setCantidad(sa);
            if(objNC.actualizarstock(objEC)==true )
            {
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el stock");
            }
        }
    }

    private void mtdcargarporcentaje() {
        ClsEIgv objEC=new ClsEIgv();
        ClsNigv objNC=new ClsNigv();
        objEC.setId(1);
        if(objNC.Cargarpocentaje(objEC)==true)
        {
            porcentaje=objEC.getCantidad();
        }
        else
        {
               JOptionPane.showMessageDialog(null, "Error al cargar el procentaje");
        } 

    }

    private void mtdgenerarboleta() {
        JasperReport repo;
            Connection con;
            try {
                Map parametro=new HashMap();
                parametro.put("serie", cuenta_serie);
                  Class.forName("com.mysql.jdbc.Driver");
                  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_electronica","root","");
                  repo=JasperCompileManager.compileReport("src/Reportes/rpt_boleta.jrxml");
                  JasperPrint jp=JasperFillManager.fillReport(repo,parametro,con);
                  JasperViewer visor = new JasperViewer(jp,false) ;
                  visor.setVisible(true) ;
                  visor.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE ); 
                    //ClassNotFoundException
            }
            catch (ClassNotFoundException| SQLException |JRException  ex) {
                    JOptionPane.showMessageDialog(null,"ocurrio este error"+ ex);
            }
    }

    private void mtdgenerarfactura() {
        JasperReport repo;
            Connection con;
            try {
                Map parametro=new HashMap();
                parametro.put("serie", cuenta_serie);
                parametro.put("igv", igv);
                parametro.put("subotal", subtotal);
                  Class.forName("com.mysql.jdbc.Driver");
                  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_electronica","root","");
                  repo=JasperCompileManager.compileReport("src/Reportes/rpts_factura.jrxml");
                  JasperPrint jp=JasperFillManager.fillReport(repo,parametro,con);
                  JasperViewer visor = new JasperViewer(jp,false) ;
                  visor.setVisible(true) ;
                  visor.setDefaultCloseOperation( javax.swing.JFrame.DISPOSE_ON_CLOSE ); 
                    //ClassNotFoundException
            }
            catch (ClassNotFoundException| SQLException |JRException  ex) {
                    JOptionPane.showMessageDialog(null,"ocurrio este error"+ ex);
            }
    }

}
