/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;
import Negocio.ClsNinicioSesion;
import Entidad.ClsEIniciosesion;
/**
 *
 * @author HUILLCA
 */
public class FrmConfcuenta extends javax.swing.JFrame {
public static String idusuario=new String();
public static String usuario=new String();
    /**
     * Creates new form FrmConfcuenta
     */
    public FrmConfcuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        txtclavenueva = new rojeru_san.RSMPassView();
        txtclaveantigua = new rojeru_san.RSMPassView();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        txtclavenueva.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtclavenueva.setPlaceholder("Escriba algo ..");
        jPanel10.add(txtclavenueva);
        txtclavenueva.setBounds(50, 160, 240, 40);

        txtclaveantigua.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtclaveantigua.setPlaceholder("Escriba algo ..");
        jPanel10.add(txtclaveantigua);
        txtclaveantigua.setBounds(50, 70, 240, 42);

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(3, 3, 89));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("INGRESE CLAVE ANTIGUA");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel31);
        jLabel31.setBounds(30, 50, 280, 80);

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(3, 3, 89));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("INGRESE CLAVE NUEVA");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel32);
        jLabel32.setBounds(30, 150, 280, 80);

        btnguardar.setBackground(new java.awt.Color(204, 255, 255));
        btnguardar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(3, 3, 89));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado_nuevo_50px_1.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setHideActionText(true);
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnguardar.setOpaque(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel10.add(btnguardar);
        btnguardar.setBounds(80, 240, 190, 59);

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear Cuenta");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        ClsEIniciosesion objEC=new ClsEIniciosesion();
        ClsNinicioSesion objNC=new ClsNinicioSesion();
        String pass=new String(txtclavenueva.getPassword());
        String pass1=new String(txtclaveantigua.getPassword());
        if(!pass1.equals("")&& !pass.equals(""))
            {
                objEC.setClave(pass1);
                objEC.setClave_nueva(pass);
                objEC.setUsuario(usuario);
                if(objNC.MtdEditarContraseña(objEC)==true)
                {
                    JOptionPane.showMessageDialog(null, "Contraseña cambiada ");
                }else
                {
                    JOptionPane.showMessageDialog(null, "Contraseña erronea");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Existen Campos vacios contraseñas");
            }
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfcuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private rojeru_san.RSMPassView txtclaveantigua;
    private rojeru_san.RSMPassView txtclavenueva;
    // End of variables declaration//GEN-END:variables
}
