/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocio.Clsventa;
import Entidad.ClsEDetalleventa;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUILLCA
 */
public class Frmdetalleboleta extends javax.swing.JInternalFrame {
DefaultTableModel modelo;
public static int codigo;
public static String nombre_empleado;
public static String nombre_cliente;
public static String serie_comprobante;
    /**
     * Creates new form Frmdetalleboleta
     */
    public Frmdetalleboleta() {
        initComponents();
        txtboleta.setText(serie_comprobante);
        txtcliente.setText(nombre_cliente);
        txtempleado.setText(nombre_empleado);
        mtdbuscar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtboleta = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtcliente = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtempleado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdetalleboleta = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 3, 89));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("N° BOLETA:");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        txtboleta.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtboleta.setForeground(new java.awt.Color(8, 91, 184));
        jPanel1.add(txtboleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 190, 20));

        txtcliente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtcliente.setForeground(new java.awt.Color(8, 91, 184));
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 190, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 3, 89));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("CLIENTE:");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 190, 20));

        txtempleado.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtempleado.setForeground(new java.awt.Color(8, 91, 184));
        jPanel1.add(txtempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 190, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(3, 3, 89));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("EMPLEADO:");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 20));

        tbdetalleboleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbdetalleboleta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 910, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable tbdetalleboleta;
    private javax.swing.JLabel txtboleta;
    private javax.swing.JLabel txtcliente;
    private javax.swing.JLabel txtempleado;
    // End of variables declaration//GEN-END:variables

    private void mtdbuscar() {
        modelo=new DefaultTableModel();
        modelo.addColumn("PRODUCTO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO VENTA");
        this.tbdetalleboleta.setModel(modelo);
        Clsventa objNC=new Clsventa();
        ClsEDetalleventa objEC=new ClsEDetalleventa();
        objEC.setId(codigo);
        String[] datos=new String[4];
        for(ClsEDetalleventa objE: objNC.Mtdbuscar(objEC))
        {
            datos[0]=objE.getNombrep();
            datos[1]=String.valueOf(objE.getCantidad());
            datos[2]=String.valueOf(objE.getPreventa());
            modelo.addRow(datos);
        }
        this.tbdetalleboleta.setModel(modelo);
    }
}
