/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsECliente;
import Negocio.ClsNCliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HUILLCA
 */
public class FrmAgregarCliente extends javax.swing.JInternalFrame {
 DefaultTableModel modelo;
    /**
     * Creates new form FrmAgregarCliente
     */
    public static int numero=0;
    public FrmAgregarCliente() {
        initComponents();
        mtdcerrcajas();
        mtdlistar();
        txtid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtemail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txnombre = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtdni = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtobservacion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btngrabar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 3, 89));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("DATOS CLIENTE:");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 90, 160, 20);

        btneditar.setBackground(new java.awt.Color(204, 255, 255));
        btneditar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btneditar.setForeground(new java.awt.Color(3, 3, 89));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.setHideActionText(true);
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneditar.setOpaque(false);
        btneditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btneditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar);
        btneditar.setBounds(790, 450, 150, 79);

        btncancelar.setBackground(new java.awt.Color(204, 255, 255));
        btncancelar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(3, 3, 89));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        btncancelar.setText("CANCELAR");
        btncancelar.setHideActionText(true);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.setOpaque(false);
        btncancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btncancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar);
        btncancelar.setBounds(960, 450, 150, 79);

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DE CLIENTES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 290, 30));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1140, 60);

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "DATOS", "DIRECCION", "CELULAR", "E-MAIL", "TIPO"
            }
        ));
        tbclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbclientes);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 130, 660, 300);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 20));

        txtemail.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(8, 91, 184));
        txtemail.setBorder(null);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel4.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, 20));

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(3, 3, 89));
        jLabel12.setText("NOMBRE C.:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 30));

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(3, 3, 89));
        jLabel14.setText("DIRECCION:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        txtdireccion.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(8, 91, 184));
        txtdireccion.setBorder(null);
        jPanel4.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, 20));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, 20));

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 3, 89));
        jLabel15.setText("E-MAIL:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 90, 30));

        txtedad.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtedad.setForeground(new java.awt.Color(8, 91, 184));
        txtedad.setBorder(null);
        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });
        jPanel4.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, 20));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 20));

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(3, 3, 89));
        jLabel16.setText("EDAD:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, 30));

        txnombre.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txnombre.setForeground(new java.awt.Color(8, 91, 184));
        txnombre.setBorder(null);
        jPanel4.add(txnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, 20));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, 20));

        txtdni.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtdni.setForeground(new java.awt.Color(8, 91, 184));
        txtdni.setBorder(null);
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });
        jPanel4.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, 20));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 190, 20));

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 3, 89));
        jLabel18.setText("DNI:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(3, 3, 89));
        jLabel17.setText("CELULAR:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, 30));

        txtcelular.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtcelular.setForeground(new java.awt.Color(8, 91, 184));
        txtcelular.setBorder(null);
        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });
        jPanel4.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, 20));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, 20));

        txtobservacion.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtobservacion.setForeground(new java.awt.Color(8, 91, 184));
        txtobservacion.setBorder(null);
        jPanel4.add(txtobservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, 20));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, 20));

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 3, 89));
        jLabel19.setText("OBSERVACION:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        txtid.setBorder(null);
        jPanel4.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 140, 20));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 120, 400, 400);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 3, 89));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("BUSCAR CLIENTE:");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 70, 180, 40);

        btngrabar.setBackground(new java.awt.Color(204, 255, 255));
        btngrabar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btngrabar.setForeground(new java.awt.Color(3, 3, 89));
        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btngrabar.setText("GRABAR");
        btngrabar.setHideActionText(true);
        btngrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btngrabar.setOpaque(false);
        btngrabar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btngrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btngrabar);
        btngrabar.setBounds(620, 450, 150, 79);

        btnnuevo.setBackground(new java.awt.Color(204, 255, 255));
        btnnuevo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(3, 3, 89));
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar_50px.png"))); // NOI18N
        btnnuevo.setText("NUEVO");
        btnnuevo.setHideActionText(true);
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setOpaque(false);
        btnnuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevo);
        btnnuevo.setBounds(450, 450, 150, 79);

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_35px.png"))); // NOI18N
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnbuscar);
        btnbuscar.setBounds(920, 70, 40, 30);
        jPanel1.add(txtbuscar);
        txtbuscar.setBounds(640, 70, 270, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        mtlimpiarcajas();
        mtdabrircaja();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        ClsECliente objEC=new ClsECliente();
        ClsNCliente objNC=new ClsNCliente();
        objEC.setDni(txtdni.getText());
        int edad_numero=Integer.parseInt(txtedad.getText());
        objEC.setEdad(edad_numero);
        objEC.setNombre(txnombre.getText());
        objEC.setDireccion(txtdireccion.getText());
        objEC.setEmail(txtemail.getText());
        objEC.setTelefono(txtcelular.getText());
        objEC.setObservacion(txtobservacion.getText());
        if(edad_numero>=18)
        {
            if(objNC.VerificarExiste(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "El Nro de DNI ya existe");
            }
            else
            {

                try {
                    objNC.MtdRegistrarCliente(objEC);
                    JOptionPane.showMessageDialog(null, "Datos Guardatos Correctamente");
                    mtlimpiarcajas();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Edad minima 18 ");
        }
        mtdlistar();
        
    }//GEN-LAST:event_btngrabarActionPerformed

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txtdniKeyTyped

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txtcelularKeyTyped

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
        if (p[i]==evt.getKeyChar()){b=1;}
 
        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txtedadKeyTyped

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        try {
            ClsECliente objEC=new ClsECliente();
            ClsNCliente objNC=new ClsNCliente();
            objEC. setId(Integer.parseInt(txtid.getText()));
            objEC.setDni(txtdni.getText());
            int edad_numero=Integer.parseInt(txtedad.getText());
            objEC.setEdad(edad_numero);
            objEC.setNombre(txnombre.getText());
            objEC.setDireccion(txtdireccion.getText());
            objEC.setEmail(txtemail.getText());
            objEC.setTelefono(txtcelular.getText());
            objEC.setObservacion(txtobservacion.getText());
            if(edad_numero>=18)
            {
                 int respuesta = JOptionPane.showConfirmDialog(this, "Desea modificar?","Confirmacion"
                ,JOptionPane.YES_NO_OPTION);
                if (respuesta==0) {
                     if(objNC.MtdModificarcliente(objEC)==true)
                        {
                            JOptionPane.showMessageDialog(null, "Datos Guardatos Correctamente");
                            mtlimpiarcajas();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Error datos incompletos");
                        }
                }else{
                    mtlimpiarcajas();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Edad minima 18 ");
            }
            mtdlistar();    
       
          } catch (Exception e) {
              e.printStackTrace();
        }
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void tbclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbclientesMouseClicked
        int seleccionar=tbclientes.rowAtPoint(evt.getPoint());
        txtid.setText(String.valueOf(tbclientes.getValueAt(seleccionar,0)));
        txtdni.setText(String.valueOf(tbclientes.getValueAt(seleccionar,1)));
        txtedad.setText(String.valueOf(tbclientes.getValueAt(seleccionar,2)));
        txnombre.setText(String.valueOf(tbclientes.getValueAt(seleccionar,3)));
        txtdireccion.setText(String.valueOf(tbclientes.getValueAt(seleccionar,4)));
        txtemail.setText(String.valueOf(tbclientes.getValueAt(seleccionar,5)));
        txtcelular.setText(String.valueOf(tbclientes.getValueAt(seleccionar,6)));
        txtobservacion.setText(String.valueOf(tbclientes.getValueAt(seleccionar,7)));
        mtdabrircaja();
    }//GEN-LAST:event_tbclientesMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        mtlimpiarcajas();
        mtdcerrcajas();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
       Mtdbuscar();
    }//GEN-LAST:event_btnbuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTextField txnombre;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtobservacion;
    // End of variables declaration//GEN-END:variables

    private void mtdabrircaja() {
        txtdni.enable(true);
        txnombre.enable(true);
        txtcelular.enable(true);
        txtdireccion.enable(true);
        txtemail.enable(true);
        txtedad.enable(true);
        txtobservacion.enable(true);
    }

    private void mtdcerrcajas() {

        txtdni.enable(false);
        txnombre.enable(false);
        txtcelular.enable(false);
        txtdireccion.enable(false);
        txtemail.enable(false);
        txtedad.enable(false);
        txtobservacion.enable(false);
    }

    private void mtlimpiarcajas() {
        txtdni.setText("");
        txnombre.setText("");
        txtcelular.setText("");
        txtdireccion.setText("");
        txtemail.setText("");
        txtedad.setText("");
        txtobservacion.setText("");
    }

    private void mtdlistar() {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("EDAD");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("EMAIL");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("OBSERVACION");
        this.tbclientes.setModel(modelo);
        ClsNCliente objNC=new ClsNCliente();
        String[] datos=new String[8];
        for(ClsECliente objE: objNC.Mtdlistar())
        {
            datos[0]=String.valueOf(objE.getId());
            datos[1]=objE.getDni();
            datos[2]=String.valueOf(objE.getEdad());
            datos[3]=objE.getNombre();
            datos[4]=objE.getDireccion();
            datos[5]=objE.getEmail();
            datos[6]=objE.getTelefono();
            datos[7]=objE.getObservacion();
            modelo.addRow(datos);
        }
        this.tbclientes.setModel(modelo);
    }

    private void Mtdbuscar() {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("EDAD");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("EMAIL");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("OBSERVACION");
        this.tbclientes.setModel(modelo);
        
        ClsNCliente objNC=new ClsNCliente();
        ClsECliente objEC=new ClsECliente();
        objEC.setDni(txtbuscar.getText());
        String[] datos=new String[8];
        for(ClsECliente objE: objNC.Mtdbuscar(objEC))
        {
            datos[0]=String.valueOf(objE.getId());
            datos[1]=objE.getDni();
            datos[2]=String.valueOf(objE.getEdad());
            datos[3]=objE.getNombre();
            datos[4]=objE.getDireccion();
            datos[5]=objE.getEmail();
            datos[6]=objE.getTelefono();
            datos[7]=objE.getObservacion();
            modelo.addRow(datos);
        }
        this.tbclientes.setModel(modelo);
    }




}
