/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author HUILLCA
 */
public class FrmBalance extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBalance
     */
    public FrmBalance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtnombree6 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtnombree7 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButton13 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtnombree10 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtnombree11 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        txtnombree12 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        txtnombree13 = new javax.swing.JTextField();
        txtnombree14 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtnombree15 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtnombree16 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        txtnombree18 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtnombree17 = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        txtnombree19 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gastos y Ganancias Mensuales");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 3, 89));
        jLabel18.setText("FECHA FINAL   :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        txtnombree6.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree6.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree6.setBorder(null);
        jPanel2.add(txtnombree6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 190, 20));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, 20));

        txtnombree7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree7.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree7.setBorder(null);
        jPanel2.add(txtnombree7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 190, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, 20));

        jButton13.setBackground(new java.awt.Color(204, 255, 255));
        jButton13.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(3, 3, 89));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir_50px_1.png"))); // NOI18N
        jButton13.setText("IMPRIMIR");
        jButton13.setHideActionText(true);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setOpaque(false);
        jButton13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 100, 80));

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(3, 3, 89));
        jLabel20.setText("FECHA INICIAL :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jButton14.setBackground(new java.awt.Color(204, 255, 255));
        jButton14.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(3, 3, 89));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px.png"))); // NOI18N
        jButton14.setText("PROCESAR");
        jButton14.setHideActionText(true);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setOpaque(false);
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 650, 100));

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 3, 89));
        jLabel19.setText("SUMATORIA TOTAL");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(3, 3, 89));
        jLabel25.setText("EMPLEADOS  :");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(3, 3, 89));
        jLabel26.setText("ALQUILER   :");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        jLabel27.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(3, 3, 89));
        jLabel27.setText("LUZ        :");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(3, 3, 89));
        jLabel28.setText("AGUA       :");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));
        jPanel6.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 120, 20));

        txtnombree10.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree10.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree10.setBorder(null);
        jPanel6.add(txtnombree10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, 20));
        jPanel6.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 20));

        txtnombree11.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree11.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree11.setBorder(null);
        jPanel6.add(txtnombree11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 20));
        jPanel6.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 120, 20));

        txtnombree12.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree12.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree12.setBorder(null);
        jPanel6.add(txtnombree12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 20));
        jPanel6.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 120, 20));

        txtnombree13.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree13.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree13.setBorder(null);
        jPanel6.add(txtnombree13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 120, 20));

        txtnombree14.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree14.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree14.setBorder(null);
        jPanel6.add(txtnombree14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, 20));
        jPanel6.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 20));

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(3, 3, 89));
        jLabel30.setText("OTRO       :");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 30));
        jPanel6.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 160, 20));

        txtnombree15.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree15.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree15.setBorder(null);
        jPanel6.add(txtnombree15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, 20));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 3, 89));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px_1.png"))); // NOI18N
        jLabel9.setText("CALCULAR");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 150));

        jLabel35.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(3, 3, 89));
        jLabel35.setText("TOTAL S/.");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 650, 140));

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(3, 3, 89));
        jLabel31.setText("PAGO EMPLEADOS/OTROS SERVICIOS");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(3, 3, 89));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px_1.png"))); // NOI18N
        jLabel8.setText("CALCULAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));
        jPanel7.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 120, 20));

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(3, 3, 89));
        jLabel32.setText("PAGO SERVICIOS :");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 30));

        jLabel34.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(3, 3, 89));
        jLabel34.setText("COMPRAS        :");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        txtnombree16.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree16.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree16.setBorder(null);
        jPanel7.add(txtnombree16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 120, 20));
        jPanel7.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, 20));

        txtnombree18.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree18.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree18.setBorder(null);
        jPanel7.add(txtnombree18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 20));

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(3, 3, 89));
        jLabel33.setText("VENTAS         :");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 30));

        txtnombree17.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree17.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree17.setBorder(null);
        jPanel7.add(txtnombree17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, 20));
        jPanel7.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, 20));

        jLabel29.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(3, 3, 89));
        jLabel29.setText("GANANCIAS S/.");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));

        txtnombree19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtnombree19.setForeground(new java.awt.Color(8, 91, 184));
        txtnombree19.setBorder(null);
        jPanel7.add(txtnombree19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 160, 20));
        jPanel7.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 650, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtnombree10;
    private javax.swing.JTextField txtnombree11;
    private javax.swing.JTextField txtnombree12;
    private javax.swing.JTextField txtnombree13;
    private javax.swing.JTextField txtnombree14;
    private javax.swing.JTextField txtnombree15;
    private javax.swing.JTextField txtnombree16;
    private javax.swing.JTextField txtnombree17;
    private javax.swing.JTextField txtnombree18;
    private javax.swing.JTextField txtnombree19;
    private javax.swing.JTextField txtnombree6;
    private javax.swing.JTextField txtnombree7;
    // End of variables declaration//GEN-END:variables
}
