/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocio.ClsNCategoriaP;
import Entidad.ClsECategoriaP;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUILLCA
 */
public class Frmcategoria extends javax.swing.JInternalFrame {
    int codigo=0;
DefaultTableModel modelo;
    /**
     * Creates new form Frmcategoria
     */
    public Frmcategoria() {
        initComponents();
        mtdlistar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcategoriap = new javax.swing.JTable();
        btnregistrar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        txtcategoria = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CATEGORIA PRODUCTO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 330, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(3, 3, 89));
        lbl.setText("CATEGORIA:");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, 20));

        tbcategoriap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbcategoriap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcategoriapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcategoriap);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 200));

        btnregistrar.setBackground(new java.awt.Color(204, 255, 255));
        btnregistrar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(3, 3, 89));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btnregistrar.setText("REGISTRAR");
        btnregistrar.setHideActionText(true);
        btnregistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnregistrar.setOpaque(false);
        btnregistrar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnregistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, 80));

        btneditar.setBackground(new java.awt.Color(204, 255, 255));
        btneditar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btneditar.setForeground(new java.awt.Color(3, 3, 89));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.setHideActionText(true);
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneditar.setOpaque(false);
        btneditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btneditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 80));

        txtcategoria.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtcategoria.setForeground(new java.awt.Color(8, 91, 184));
        txtcategoria.setBorder(null);
        jPanel1.add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        ClsECategoriaP objEC=new ClsECategoriaP();
        ClsNCategoriaP objNC=new ClsNCategoriaP();
        Date date=new Date();
        DateFormat fechaHora=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        objEC.setCategoria(txtcategoria.getText());
        objEC.setFecha(fechaHora.format(date));
        if(objNC.mtdguardarcategoria(objEC)==true)
        {
            JOptionPane.showMessageDialog(null, "Datos Guardatos correctamente");
            mtdlistar();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        }
        

    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        ClsECategoriaP objEC=new ClsECategoriaP();
        ClsNCategoriaP objNC=new ClsNCategoriaP();
        objEC.setId(codigo);
        objEC.setCategoria(txtcategoria.getText());
        if(objNC.mtdmodificarcategoria(objEC)==true)
        {
            JOptionPane.showMessageDialog(null, "Datos MOdificados correctamente");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error al ingresar los datos");
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void tbcategoriapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcategoriapMouseClicked
        int seleccionar=tbcategoriap.rowAtPoint(evt.getPoint());
        String codigol=String.valueOf(tbcategoriap.getValueAt(seleccionar,0));
        codigo=Integer.parseInt(codigol);
        txtcategoria.setText(String.valueOf(tbcategoriap.getValueAt(seleccionar,1)));
    }//GEN-LAST:event_tbcategoriapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl;
    private javax.swing.JTable tbcategoriap;
    private javax.swing.JTextField txtcategoria;
    // End of variables declaration//GEN-END:variables

    private void mtdlistar() {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("FECHA");
        this.tbcategoriap.setModel(modelo);
        ClsNCategoriaP objNC=new ClsNCategoriaP();
        String[] datos=new String[3];
        for(ClsECategoriaP objE: objNC.MtdListar())
        {
            datos[0]=String.valueOf(objE.getId());
            datos[1]=objE.getCategoria();
            datos[2]=objE.getFecha();
            modelo.addRow(datos);
        }
        this.tbcategoriap.setModel(modelo);
    }
}
