/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.ClsEproducto;
import Negocio.ClsNcaja;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUILLCA
 */
public class FrmCaja extends javax.swing.JInternalFrame {
DefaultTableModel modelo;
    /**
     * Creates new form FrmCaja
     */
    public FrmCaja() {
        initComponents();
        Date date=new Date();
        DateFormat fechaHora=new SimpleDateFormat("yyyy-MM-dd");
        txtfecha.setText(fechaHora.format(date));
        //mtdlistarcompras();
        //mtdlistarventas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbcompras = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbventas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        pnlcaja = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtimporte = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtsalida = new javax.swing.JLabel();
        txtentrada = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txttotal = new javax.swing.JLabel();
        btnimprimir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnabrircaja = new javax.swing.JButton();
        btncerrarcaja = new javax.swing.JButton();
        btncalcular = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1360, 610));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tbcompras.setBackground(new java.awt.Color(153, 204, 255));
        tbcompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUCTO", "MARCA", "SERIE", "COSTO", "CANTIDAD", "SOCIEDAD", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbcompras.setOpaque(false);
        tbcompras.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tbcompras.setSelectionForeground(new java.awt.Color(51, 0, 51));
        jScrollPane2.setViewportView(tbcompras);

        jTabbedPane1.addTab("CONTROL DE COMPRAS", jScrollPane2);

        tbventas.setBackground(new java.awt.Color(153, 153, 255));
        tbventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOLETA", "CODIGO", "MARCA", "SERIE", "CANT.", "PRECIO", "IMPORTE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbventas.setOpaque(false);
        tbventas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbventas.setSelectionForeground(new java.awt.Color(153, 255, 0));
        jScrollPane1.setViewportView(tbventas);

        jTabbedPane1.addTab("CONTROL DE VENTAS", jScrollPane1);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 960, 480));

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROL DE ENTRADA Y SALIDA DE DINERO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 540, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 60));

        txtfecha.setBackground(new java.awt.Color(255, 255, 255));
        txtfecha.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        txtfecha.setForeground(new java.awt.Color(3, 3, 89));
        txtfecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtfecha.setText("DD/MM/AAAA");
        txtfecha.setOpaque(true);
        jPanel1.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 30));

        pnlcaja.setBackground(new java.awt.Color(255, 255, 255));
        pnlcaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlcaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(3, 3, 89));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("IMPORTE INICIAL S/.");
        jLabel12.setOpaque(true);
        pnlcaja.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 3, 89));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ENTRADA S/.");
        jLabel15.setOpaque(true);
        pnlcaja.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 130, 20));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(3, 3, 89));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("SALIDA S/.");
        jLabel16.setOpaque(true);
        pnlcaja.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, 20));

        jSeparator1.setForeground(new java.awt.Color(3, 3, 89));
        pnlcaja.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, 10));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(3, 3, 89));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("TOTAL EF. S/.");
        jLabel17.setOpaque(true);
        pnlcaja.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 20));

        txtimporte.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtimporte.setForeground(new java.awt.Color(3, 3, 89));
        txtimporte.setBorder(null);
        pnlcaja.add(txtimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 150, 30));
        pnlcaja.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 10));
        pnlcaja.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 10));

        txtsalida.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtsalida.setForeground(new java.awt.Color(3, 3, 89));
        pnlcaja.add(txtsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));

        txtentrada.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtentrada.setForeground(new java.awt.Color(3, 3, 89));
        pnlcaja.add(txtentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));
        pnlcaja.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 10));
        pnlcaja.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 10));

        txttotal.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txttotal.setForeground(new java.awt.Color(3, 3, 89));
        pnlcaja.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 30));

        jPanel1.add(pnlcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 360, 290));

        btnimprimir.setBackground(new java.awt.Color(204, 255, 255));
        btnimprimir.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnimprimir.setForeground(new java.awt.Color(3, 3, 89));
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir_50px_1.png"))); // NOI18N
        btnimprimir.setText("IMPRIMIR");
        btnimprimir.setHideActionText(true);
        btnimprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnimprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnimprimir.setOpaque(false);
        jPanel1.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 180, 60));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(3, 3, 89));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("FECHA :");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        btnabrircaja.setBackground(new java.awt.Color(204, 255, 255));
        btnabrircaja.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnabrircaja.setForeground(new java.awt.Color(3, 3, 89));
        btnabrircaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/activar_50px.png"))); // NOI18N
        btnabrircaja.setText("ABRIR CAJA");
        btnabrircaja.setHideActionText(true);
        btnabrircaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnabrircaja.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnabrircaja.setOpaque(false);
        btnabrircaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrircajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnabrircaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 170, 60));

        btncerrarcaja.setBackground(new java.awt.Color(204, 255, 255));
        btncerrarcaja.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btncerrarcaja.setForeground(new java.awt.Color(3, 3, 89));
        btncerrarcaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        btncerrarcaja.setText("CERRAR CAJA");
        btncerrarcaja.setHideActionText(true);
        btncerrarcaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncerrarcaja.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btncerrarcaja.setOpaque(false);
        jPanel1.add(btncerrarcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 180, 60));

        btncalcular.setBackground(new java.awt.Color(204, 255, 255));
        btncalcular.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btncalcular.setForeground(new java.awt.Color(3, 3, 89));
        btncalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calcular_50px.png"))); // NOI18N
        btncalcular.setText("CALCULAR");
        btncalcular.setHideActionText(true);
        btncalcular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncalcular.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btncalcular.setOpaque(false);
        jPanel1.add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrircajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrircajaActionPerformed
          
    }//GEN-LAST:event_btnabrircajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabrircaja;
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncerrarcaja;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlcaja;
    private javax.swing.JTable tbcompras;
    private javax.swing.JTable tbventas;
    private javax.swing.JLabel txtentrada;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JTextField txtimporte;
    private javax.swing.JLabel txtsalida;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables

    private void mtdlistarcompras() {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("PROVEEDOR");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("PRECIO COMPRA");
        modelo.addColumn("PRECIO VENTA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("MARCA");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("FECHA ");
        this.tbcompras.setModel(modelo);
        ClsNcaja objNC=new ClsNcaja();
        ClsEproducto objEC=new ClsEproducto();
        objEC.setFecha(txtfecha.getText());
        String[] datos=new String[11];
        for(ClsEproducto objE: objNC.Mtdlistarfecha(objEC))
        {
            datos[0]=String.valueOf(objE.getId_producto());
            datos[1]=objE.getCategoria();
            datos[2]=objE.getRuc();
            datos[3]=String.valueOf(objE.getCantidad());
            datos[4]=String.valueOf(objE.getPrecio_compra());
            datos[5]=String.valueOf(objE.getPrecio_venta());
            datos[6]=objE.getNombre();
            datos[7]=objE.getMarca();
            datos[8]=objE.getDescripcion();
            datos[9]=objE.getFecha();
            modelo.addRow(datos);
        }
        this.tbcompras.setModel(modelo);
    }

    private void mtdlistarventas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
