/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;
import AppPackage.AnimationClass;
import Entidad.ClsEIniciosesion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
/**
 *
 * @author HUILLCA
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    ClsEIniciosesion objEC;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public static int op=0;
    public FrmMenuPrincipal() {
        initComponents();
    }
    public FrmMenuPrincipal(ClsEIniciosesion objEC)
    {
        initComponents();
        this.objEC = objEC;
        lbltipo.setText(String.valueOf(objEC.getCargo_empleado()));
        
        if(objEC.getCargo_empleado()==1)
        {
            op=1;
            lbltipo.setText(String.valueOf(objEC.getUsuario()));
        }
        else if(objEC.getCargo_empleado()==2)
        {
            op=2;
            lbltipo.setText("2");
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnproveedores = new javax.swing.JLabel();
        btnproductos = new javax.swing.JLabel();
        btnempleado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JLabel();
        btnminimizar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbltipo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JLabel();
        btnventas = new javax.swing.JLabel();
        btnstock = new javax.swing.JLabel();
        btnclientes = new javax.swing.JLabel();
        btnboleta = new javax.swing.JLabel();
        btnreportes = new javax.swing.JLabel();
        btncaja = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JLabel();
        btnplanilla = new javax.swing.JLabel();
        btncerrar_sesion = new javax.swing.JLabel();
        btnbalance1 = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/iconos/Fondo.jpg"));
        Image image = icon.getImage();
        DpanEscritorio = new javax.swing.JDesktopPane()
        {
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnproveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnproveedores.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnproveedores.setForeground(new java.awt.Color(70, 108, 170));
        btnproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/proveedores_24px.png"))); // NOI18N
        btnproveedores.setText("Proveedores");
        btnproveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnproveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnproveedores.setOpaque(true);
        btnproveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproveedoresMouseClicked(evt);
            }
        });
        getContentPane().add(btnproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 140, 130, 30));

        btnproductos.setBackground(new java.awt.Color(255, 255, 255));
        btnproductos.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnproductos.setForeground(new java.awt.Color(70, 108, 170));
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/productos_24px.png"))); // NOI18N
        btnproductos.setText("Productos");
        btnproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnproductos.setOpaque(true);
        btnproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproductosMouseClicked(evt);
            }
        });
        getContentPane().add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 180, 130, 30));

        btnempleado.setBackground(new java.awt.Color(255, 255, 255));
        btnempleado.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnempleado.setForeground(new java.awt.Color(70, 108, 170));
        btnempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado_24px.png"))); // NOI18N
        btnempleado.setText("Empleado");
        btnempleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnempleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnempleado.setOpaque(true);
        btnempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnempleadoMouseClicked(evt);
            }
        });
        getContentPane().add(btnempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 220, 130, 30));

        jPanel4.setBackground(new java.awt.Color(228, 94, 46));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar_26px.png"))); // NOI18N
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });
        jPanel4.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 30, 40));

        btnminimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minimizar_26px.png"))); // NOI18N
        btnminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizarMouseClicked(evt);
            }
        });
        jPanel4.add(btnminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, -1, 40));

        jButton1.setBackground(new java.awt.Color(228, 94, 46));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_settings_20px_1.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        lbltipo.setText("jLabel1");
        jPanel4.add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(70, 108, 170));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu40px.png"))); // NOI18N
        btnmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuMouseClicked(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, -1, -1));

        btnventas.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnventas.setForeground(new java.awt.Color(70, 108, 170));
        btnventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventas_35px.png"))); // NOI18N
        btnventas.setText("Ventas");
        btnventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnventasMouseClicked(evt);
            }
        });
        jPanel1.add(btnventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 90, 80));

        btnstock.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnstock.setForeground(new java.awt.Color(70, 108, 170));
        btnstock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stock_35px.png"))); // NOI18N
        btnstock.setText("Stock");
        btnstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnstock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnstockMouseClicked(evt);
            }
        });
        jPanel1.add(btnstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        btnclientes.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnclientes.setForeground(new java.awt.Color(70, 108, 170));
        btnclientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clientes_35px.png"))); // NOI18N
        btnclientes.setText("Clientes");
        btnclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclientesMouseClicked(evt);
            }
        });
        jPanel1.add(btnclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 80));

        btnboleta.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnboleta.setForeground(new java.awt.Color(70, 108, 170));
        btnboleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnboleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boleta_35px.png"))); // NOI18N
        btnboleta.setText("Boleta");
        btnboleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnboleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnboleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnboleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnboletaMouseClicked(evt);
            }
        });
        jPanel1.add(btnboleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 90, 80));

        btnreportes.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(70, 108, 170));
        btnreportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte_35px.png"))); // NOI18N
        btnreportes.setText("Reportes");
        btnreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreportesMouseClicked(evt);
            }
        });
        jPanel1.add(btnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 90, 80));

        btncaja.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btncaja.setForeground(new java.awt.Color(70, 108, 170));
        btncaja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/caja_35px.png"))); // NOI18N
        btncaja.setText("Caja");
        btncaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncajaMouseClicked(evt);
            }
        });
        jPanel1.add(btncaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 90, 80));

        btnregistrar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(70, 108, 170));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar_24px.png"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 130, 30));

        btnplanilla.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnplanilla.setForeground(new java.awt.Color(70, 108, 170));
        btnplanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/creditos_24px.png"))); // NOI18N
        btnplanilla.setText("Planilla");
        btnplanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnplanilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnplanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 140, 30));

        btncerrar_sesion.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btncerrar_sesion.setForeground(new java.awt.Color(70, 108, 170));
        btncerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar_sesion_24px.png"))); // NOI18N
        btncerrar_sesion.setText("Cerrar Sesion");
        btncerrar_sesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncerrar_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrar_sesionMouseClicked(evt);
            }
        });
        jPanel1.add(btncerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 140, -1));

        btnbalance1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnbalance1.setForeground(new java.awt.Color(70, 108, 170));
        btnbalance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbalance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/valance_35px.png"))); // NOI18N
        btnbalance1.setText("Balance");
        btnbalance1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbalance1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbalance1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbalance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbalance1MouseClicked(evt);
            }
        });
        jPanel1.add(btnbalance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 90, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1360, 80));

        javax.swing.GroupLayout DpanEscritorioLayout = new javax.swing.GroupLayout(DpanEscritorio);
        DpanEscritorio.setLayout(DpanEscritorioLayout);
        DpanEscritorioLayout.setHorizontalGroup(
            DpanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        DpanEscritorioLayout.setVerticalGroup(
            DpanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(DpanEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1360, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked
        int dialogo=JOptionPane.YES_OPTION;
        int resultado=JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?","Salir",dialogo);
        if(resultado==0)
        {
            System.exit(0);
        }
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_btncerrarMouseClicked

    private void btnminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseClicked
        this.setState(FrmLogin.ICONIFIED);
    }//GEN-LAST:event_btnminimizarMouseClicked

    private void btnmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseClicked
        
        if(op==1)
        {
            AnimationClass abrir_menu_principal=new AnimationClass();
        abrir_menu_principal.jLabelXLeft(1400, 1140 , 5, 5, btncerrar_sesion);
        abrir_menu_principal.jLabelXLeft(1400, 990 , 5, 5, btnregistrar);
        abrir_menu_principal.jLabelXLeft(1400, 830 , 5, 5, btnplanilla);
        
        AnimationClass cerrar_menu_principal=new AnimationClass();
        cerrar_menu_principal.jLabelXRight(1140 , 1400, 5, 5, btncerrar_sesion);
        cerrar_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnregistrar);
        cerrar_menu_principal.jLabelXRight(830 , 1400, 5, 5, btnplanilla);
        
        AnimationClass cerrar_sub_menu_principal=new AnimationClass();
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnproductos);
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnempleado);
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnproveedores);
        }
        else if(op==2)
        {
        AnimationClass abrir_menu_principal=new AnimationClass();
        abrir_menu_principal.jLabelXLeft(1400, 1140 , 5, 5, btncerrar_sesion);

        
        AnimationClass cerrar_menu_principal=new AnimationClass();
        cerrar_menu_principal.jLabelXRight(1140 , 1400, 5, 5, btncerrar_sesion);
        }

    }//GEN-LAST:event_btnmenuMouseClicked

    private void btnregistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMouseClicked
        AnimationClass abrir_sub_menu_principal=new AnimationClass();
        abrir_sub_menu_principal.jLabelXLeft(1400 , 990, 5, 5, btnproductos);
        abrir_sub_menu_principal.jLabelXLeft(1400 , 990, 5, 5, btnempleado);
        abrir_sub_menu_principal.jLabelXLeft(1400 , 990, 5, 5, btnproveedores);
        
        AnimationClass cerrar_sub_menu_principal=new AnimationClass();
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnproductos);
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnempleado);
        cerrar_sub_menu_principal.jLabelXRight(990 , 1400, 5, 5, btnproveedores);
    }//GEN-LAST:event_btnregistrarMouseClicked

    private void btnproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproductosMouseClicked
        FrmAgregarProductos frm=new FrmAgregarProductos();
        DpanEscritorio.add(frm);
        frm.show();
        
    }//GEN-LAST:event_btnproductosMouseClicked

    private void btnventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnventasMouseClicked
        FrmVentas frm=new FrmVentas();
        DpanEscritorio.add(frm);
        frm.show();
    }//GEN-LAST:event_btnventasMouseClicked

    private void btnstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstockMouseClicked
        FrmListarProductos frm=new FrmListarProductos();
        DpanEscritorio.add(frm);
        frm.show();
    }//GEN-LAST:event_btnstockMouseClicked

    private void btnclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclientesMouseClicked
        FrmAgregarCliente frm=new FrmAgregarCliente();
        DpanEscritorio.add(frm);
        frm.show();
    }//GEN-LAST:event_btnclientesMouseClicked

    private void btnboletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnboletaMouseClicked
        Frmboleta.idvendedor=objEC.getId();

        Frmboleta frm=new Frmboleta();
            
        DpanEscritorio.add(frm);
        frm.show();     
    }//GEN-LAST:event_btnboletaMouseClicked

    private void btnreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreportesMouseClicked
        FrmReportes frm=new FrmReportes();
        DpanEscritorio.add(frm);
        frm.show(); 
    }//GEN-LAST:event_btnreportesMouseClicked

    private void btncajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncajaMouseClicked
        FrmCaja frm=new FrmCaja();
        DpanEscritorio.add(frm);
        frm.show();      
    }//GEN-LAST:event_btncajaMouseClicked

    private void btncerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrar_sesionMouseClicked
        ///////////falta xD
    }//GEN-LAST:event_btncerrar_sesionMouseClicked

    private void btnproveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproveedoresMouseClicked
        FrmAgregarProveedores frm=new FrmAgregarProveedores();
        DpanEscritorio.add(frm);
        frm.show(); 
    }//GEN-LAST:event_btnproveedoresMouseClicked

    private void btnempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnempleadoMouseClicked
        FrmRegistroEmpleado frm=new FrmRegistroEmpleado();
        DpanEscritorio.add(frm);
        frm.show(); 
    }//GEN-LAST:event_btnempleadoMouseClicked

    private void btnbalance1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbalance1MouseClicked
        FrmBalance frm=new FrmBalance();
        DpanEscritorio.add(frm);
        frm.show();
    }//GEN-LAST:event_btnbalance1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmConfcuenta.usuario=String.valueOf(objEC.getUsuario());
        FrmConfcuenta frm=new FrmConfcuenta();
        frm.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DpanEscritorio;
    private javax.swing.JLabel btnbalance1;
    private javax.swing.JLabel btnboleta;
    private javax.swing.JLabel btncaja;
    private javax.swing.JLabel btncerrar;
    private javax.swing.JLabel btncerrar_sesion;
    private javax.swing.JLabel btnclientes;
    private javax.swing.JLabel btnempleado;
    private javax.swing.JLabel btnmenu;
    private javax.swing.JLabel btnminimizar;
    private javax.swing.JLabel btnplanilla;
    private javax.swing.JLabel btnproductos;
    private javax.swing.JLabel btnproveedores;
    private javax.swing.JLabel btnregistrar;
    private javax.swing.JLabel btnreportes;
    private javax.swing.JLabel btnstock;
    private javax.swing.JLabel btnventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbltipo;
    // End of variables declaration//GEN-END:variables


}
