/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Entidad.ClsEEmpleado;
import Negocio.*;
import com.mysql.cj.xdevapi.JsonParser;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import Negocio.ClsTabla;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author HUILLCA
 */
public class FrmRegistroEmpleado extends javax.swing.JInternalFrame {
    File ruta;
    Image IMG;
    public String ruta1="";
    DefaultTableModel modelo;
    /**
     * Creates new form FrmRegistroEmpleado
     */
    public FrmRegistroEmpleado() {
        initComponents();
        cbocargo.removeAllItems();
        cboAreaTrb.removeAllItems();
        cboAreaTrb.addItem("Seleccione ");
        cbocargo.addItem("Seleccione ");
        mtdmostrarcombo();
        mtdlistartabla();
        txtid.setVisible(false);
        mtdbotones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpsexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtdni = new rojeru_san.RSMTextFull();
        txtnombre = new rojeru_san.RSMTextFull();
        txtemail1 = new rojeru_san.RSMTextFull();
        txttelefono = new rojeru_san.RSMTextFull();
        txtdireccion4 = new rojeru_san.RSMTextFull();
        jLabel24 = new javax.swing.JLabel();
        rbtnfemenino = new javax.swing.JRadioButton();
        rbtnmasculino = new javax.swing.JRadioButton();
        btnbuscardni = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cbocargo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        txtsueldo = new rojeru_san.RSMTextFull();
        jPanel6 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btnnuevo1 = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnseleccionarfoto = new rojerusan.RSButtonIconD();
        lblimagen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnactivar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnsuspender = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cboAreaTrb = new javax.swing.JComboBox();
        txtsueldoM = new javax.swing.JTextField();
        txtdniM = new javax.swing.JTextField();
        txtdireccionM = new javax.swing.JTextField();
        txtemailM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txttelefonoM = new javax.swing.JTextField();
        txtnombreM = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        btngenerarcuenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistrosEmpl = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnbloquearcuenta = new javax.swing.JButton();
        btndesbloquearcuenta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(26, 68, 147));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Empleado");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 70));

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setForeground(new java.awt.Color(3, 3, 89));
        jTabbedPane2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTabbedPane2.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(3, 3, 89));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("INGRESE DNI");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel15);
        jLabel15.setBounds(40, 20, 260, 70);

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(3, 3, 89));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("INGRESE NOMBRES C.");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel16);
        jLabel16.setBounds(370, 20, 300, 70);

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(3, 3, 89));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("INGRESE DIRECCION");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel18);
        jLabel18.setBounds(40, 120, 260, 70);

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(3, 3, 89));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("INGRESE EMAIL");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel19);
        jLabel19.setBounds(370, 120, 300, 70);

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(3, 3, 89));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("INGRESE TELEFONO");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel21);
        jLabel21.setBounds(40, 210, 260, 70);

        txtdni.setAlignmentX(0.2F);
        txtdni.setAlignmentY(0.2F);
        txtdni.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdni.setPlaceholder("00000000");
        txtdni.setSoloNumeros(true);
        jPanel9.add(txtdni);
        txtdni.setBounds(60, 30, 220, 40);

        txtnombre.setAlignmentX(0.2F);
        txtnombre.setAlignmentY(0.2F);
        txtnombre.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtnombre.setPlaceholder("Escriba algo....");
        jPanel9.add(txtnombre);
        txtnombre.setBounds(400, 30, 250, 40);

        txtemail1.setAlignmentX(0.2F);
        txtemail1.setAlignmentY(0.2F);
        txtemail1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtemail1.setPlaceholder("nombre@dominio.com");
        jPanel9.add(txtemail1);
        txtemail1.setBounds(400, 130, 250, 40);

        txttelefono.setAlignmentX(0.2F);
        txttelefono.setAlignmentY(0.2F);
        txttelefono.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txttelefono.setPlaceholder("000000000");
        txttelefono.setSoloNumeros(true);
        jPanel9.add(txttelefono);
        txttelefono.setBounds(60, 220, 220, 40);

        txtdireccion4.setAlignmentX(0.2F);
        txtdireccion4.setAlignmentY(0.2F);
        txtdireccion4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdireccion4.setPlaceholder("Escriba algo....");
        jPanel9.add(txtdireccion4);
        txtdireccion4.setBounds(60, 130, 220, 40);

        jLabel24.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(3, 3, 89));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("SELECCIONE SEXO");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel24);
        jLabel24.setBounds(370, 210, 300, 70);

        rbtnfemenino.setText("Femenino");
        jPanel9.add(rbtnfemenino);
        rbtnfemenino.setBounds(530, 230, 110, 23);

        rbtnmasculino.setText("Masculino");
        jPanel9.add(rbtnmasculino);
        rbtnmasculino.setBounds(400, 230, 110, 23);

        btnbuscardni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_35px.png"))); // NOI18N
        btnbuscardni.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnbuscardniMouseMoved(evt);
            }
        });
        btnbuscardni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscardniMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscardniMouseExited(evt);
            }
        });
        jPanel9.add(btnbuscardni);
        btnbuscardni.setBounds(310, 20, 40, 50);

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(3, 3, 89));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("CARGO EMPLEADO");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel30);
        jLabel30.setBounds(40, 320, 260, 70);

        cbocargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "VENDEDOR" }));
        jPanel9.add(cbocargo);
        cbocargo.setBounds(80, 330, 180, 30);

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(3, 3, 89));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("INGRESE SUELDO");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel28);
        jLabel28.setBounds(370, 320, 300, 70);

        txtsueldo.setAlignmentX(0.2F);
        txtsueldo.setAlignmentY(0.2F);
        txtsueldo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtsueldo.setPlaceholder("S/. 00.0");
        jPanel9.add(txtsueldo);
        txtsueldo.setBounds(390, 330, 250, 40);

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 700, 430));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(204, 255, 255));
        btncancelar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(3, 3, 89));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setHideActionText(true);
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btncancelar.setOpaque(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel6.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 70));

        btnregistrar.setBackground(new java.awt.Color(204, 255, 255));
        btnregistrar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(3, 3, 89));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado_registrar_50px.png"))); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.setHideActionText(true);
        btnregistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnregistrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnregistrar.setOpaque(false);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        jPanel6.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 70));

        btnnuevo1.setBackground(new java.awt.Color(204, 255, 255));
        btnnuevo1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnnuevo1.setForeground(new java.awt.Color(3, 3, 89));
        btnnuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado_nuevo_50px_1.png"))); // NOI18N
        btnnuevo1.setText("Nuevo");
        btnnuevo1.setHideActionText(true);
        btnnuevo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnnuevo1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnnuevo1.setOpaque(false);
        btnnuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevo1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnnuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, 70));

        btnsalir.setBackground(new java.awt.Color(204, 255, 255));
        btnsalir.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(3, 3, 89));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir_50px.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setHideActionText(true);
        btnsalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnsalir.setOpaque(false);
        jPanel6.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 200, 70));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 250, 430));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(null);

        btnseleccionarfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/foto_persona_40px_1.png"))); // NOI18N
        btnseleccionarfoto.setText("Seleccionar Perfil");
        btnseleccionarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarfotoActionPerformed(evt);
            }
        });
        jPanel12.add(btnseleccionarfoto);
        btnseleccionarfoto.setBounds(40, 360, 200, 40);

        lblimagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.add(lblimagen);
        lblimagen.setBounds(40, 40, 200, 250);

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 430));

        jTabbedPane2.addTab("Registar Empleado", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnactivar.setBackground(new java.awt.Color(204, 255, 255));
        btnactivar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnactivar.setForeground(new java.awt.Color(3, 3, 89));
        btnactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/activar_50px.png"))); // NOI18N
        btnactivar.setText("ACTIVAR");
        btnactivar.setHideActionText(true);
        btnactivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnactivar.setOpaque(false);
        btnactivar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnactivar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactivarActionPerformed(evt);
            }
        });
        jPanel5.add(btnactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, 80));

        btnmodificar.setBackground(new java.awt.Color(204, 255, 255));
        btnmodificar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(3, 3, 89));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.setHideActionText(true);
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setOpaque(false);
        btnmodificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel5.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        btncancel.setBackground(new java.awt.Color(204, 255, 255));
        btncancel.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(3, 3, 89));
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar_50px.png"))); // NOI18N
        btncancel.setText("CANCELAR");
        btncancel.setHideActionText(true);
        btncancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancel.setOpaque(false);
        btncancel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btncancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 80));

        btnsuspender.setBackground(new java.awt.Color(204, 255, 255));
        btnsuspender.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnsuspender.setForeground(new java.awt.Color(3, 3, 89));
        btnsuspender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/suspender_50px.png"))); // NOI18N
        btnsuspender.setText("SUSPENDER");
        btnsuspender.setHideActionText(true);
        btnsuspender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsuspender.setOpaque(false);
        btnsuspender.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnsuspender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuspenderActionPerformed(evt);
            }
        });
        jPanel5.add(btnsuspender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 80));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 320, 200));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(3, 3, 89));
        jLabel5.setForeground(new java.awt.Color(3, 3, 89));
        jLabel5.setText("D N I                     :");
        jPanel7.add(jLabel5);
        jLabel5.setBounds(20, 20, 100, 14);
        jPanel7.add(jSeparator6);
        jSeparator6.setBounds(130, 40, 190, 10);
        jPanel7.add(jSeparator5);
        jSeparator5.setBounds(130, 80, 190, 10);

        jLabel10.setBackground(new java.awt.Color(3, 3, 89));
        jLabel10.setForeground(new java.awt.Color(3, 3, 89));
        jLabel10.setText("C E L U L A R      :");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(340, 60, 100, 14);

        jLabel9.setBackground(new java.awt.Color(3, 3, 89));
        jLabel9.setForeground(new java.awt.Color(3, 3, 89));
        jLabel9.setText("E - M A I L        :");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(346, 20, 90, 14);

        jLabel8.setBackground(new java.awt.Color(3, 3, 89));
        jLabel8.setForeground(new java.awt.Color(3, 3, 89));
        jLabel8.setText("D I R E C C I Ó N :");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(20, 100, 110, 14);
        jPanel7.add(jSeparator7);
        jSeparator7.setBounds(130, 120, 190, 10);
        jPanel7.add(jSeparator1);
        jSeparator1.setBounds(440, 40, 220, 10);
        jPanel7.add(jSeparator3);
        jSeparator3.setBounds(440, 80, 220, 10);

        jLabel3.setBackground(new java.awt.Color(3, 3, 89));
        jLabel3.setForeground(new java.awt.Color(3, 3, 89));
        jLabel3.setText("A R E A.  T R A B A J O     :");
        jPanel7.add(jLabel3);
        jLabel3.setBounds(20, 150, 180, 14);

        jLabel11.setBackground(new java.awt.Color(3, 3, 89));
        jLabel11.setForeground(new java.awt.Color(3, 3, 89));
        jLabel11.setText("S U E L D O         : ");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(340, 100, 100, 14);
        jPanel7.add(jSeparator2);
        jSeparator2.setBounds(440, 120, 220, 10);

        cboAreaTrb.setBackground(new java.awt.Color(0, 0, 0));
        cboAreaTrb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendedor" }));
        jPanel7.add(cboAreaTrb);
        cboAreaTrb.setBounds(160, 140, 200, 30);

        txtsueldoM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtsueldoM.setForeground(new java.awt.Color(0, 0, 51));
        txtsueldoM.setBorder(null);
        txtsueldoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsueldoMKeyTyped(evt);
            }
        });
        jPanel7.add(txtsueldoM);
        txtsueldoM.setBounds(440, 90, 220, 30);

        txtdniM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdniM.setForeground(new java.awt.Color(0, 0, 51));
        txtdniM.setBorder(null);
        txtdniM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniMKeyTyped(evt);
            }
        });
        jPanel7.add(txtdniM);
        txtdniM.setBounds(130, 10, 190, 30);

        txtdireccionM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtdireccionM.setForeground(new java.awt.Color(0, 0, 51));
        txtdireccionM.setBorder(null);
        jPanel7.add(txtdireccionM);
        txtdireccionM.setBounds(130, 90, 190, 30);

        txtemailM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtemailM.setForeground(new java.awt.Color(0, 0, 51));
        txtemailM.setBorder(null);
        jPanel7.add(txtemailM);
        txtemailM.setBounds(440, 10, 220, 30);

        jLabel12.setBackground(new java.awt.Color(3, 3, 89));
        jLabel12.setForeground(new java.awt.Color(3, 3, 89));
        jLabel12.setText("N O M B R E S       :");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(20, 60, 120, 14);

        txttelefonoM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txttelefonoM.setForeground(new java.awt.Color(0, 0, 51));
        txttelefonoM.setBorder(null);
        txttelefonoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoMKeyTyped(evt);
            }
        });
        jPanel7.add(txttelefonoM);
        txttelefonoM.setBounds(440, 50, 220, 30);

        txtnombreM.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtnombreM.setForeground(new java.awt.Color(0, 0, 51));
        txtnombreM.setBorder(null);
        jPanel7.add(txtnombreM);
        txtnombreM.setBounds(130, 50, 190, 30);

        txtid.setBorder(null);
        jPanel7.add(txtid);
        txtid.setBounds(10, 130, 120, 14);

        btngenerarcuenta.setBackground(new java.awt.Color(204, 255, 255));
        btngenerarcuenta.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btngenerarcuenta.setForeground(new java.awt.Color(3, 3, 89));
        btngenerarcuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado_nuevo_50px_1.png"))); // NOI18N
        btngenerarcuenta.setText("Generar Cuenta");
        btngenerarcuenta.setHideActionText(true);
        btngenerarcuenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btngenerarcuenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btngenerarcuenta.setOpaque(false);
        btngenerarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarcuentaActionPerformed(evt);
            }
        });
        jPanel7.add(btngenerarcuenta);
        btngenerarcuenta.setBounds(410, 140, 230, 59);

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 700, 220));

        tblRegistrosEmpl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosEmplMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistrosEmpl);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1270, 190));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        btnbloquearcuenta.setBackground(new java.awt.Color(204, 255, 255));
        btnbloquearcuenta.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btnbloquearcuenta.setForeground(new java.awt.Color(3, 3, 89));
        btnbloquearcuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir_50px.png"))); // NOI18N
        btnbloquearcuenta.setText("BLOQUEAR");
        btnbloquearcuenta.setHideActionText(true);
        btnbloquearcuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbloquearcuenta.setOpaque(false);
        btnbloquearcuenta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnbloquearcuenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(btnbloquearcuenta);
        btnbloquearcuenta.setBounds(30, 10, 140, 80);

        btndesbloquearcuenta.setBackground(new java.awt.Color(204, 255, 255));
        btndesbloquearcuenta.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btndesbloquearcuenta.setForeground(new java.awt.Color(3, 3, 89));
        btndesbloquearcuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir_50px.png"))); // NOI18N
        btndesbloquearcuenta.setText("DESBLOQUEAR");
        btndesbloquearcuenta.setHideActionText(true);
        btndesbloquearcuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndesbloquearcuenta.setOpaque(false);
        btndesbloquearcuenta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btndesbloquearcuenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(btndesbloquearcuenta);
        btndesbloquearcuenta.setBounds(30, 110, 140, 80);

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 190, 200));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(3, 3, 89));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("USUARIO :");
        jLabel13.setOpaque(true);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(3, 3, 89));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("EMPLEADO :");
        jLabel14.setOpaque(true);
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jTabbedPane2.addTab("Ver Empleado", jPanel4);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1310, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRegistrosEmplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosEmplMouseClicked
        int seleccionar=tblRegistrosEmpl.rowAtPoint(evt.getPoint());
        txtid.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,0)));
        txtdniM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,1)));
        cboAreaTrb.setSelectedItem(tblRegistrosEmpl.getValueAt(seleccionar,2));
        txtnombreM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,3)));
        txtdireccionM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,4)));
        txtemailM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,5)));
        txttelefonoM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,6)));
        txtsueldoM.setText(String.valueOf(tblRegistrosEmpl.getValueAt(seleccionar,9)));
        mtdmostrarimagen();
    }//GEN-LAST:event_tblRegistrosEmplMouseClicked

    private void btngenerarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarcuentaActionPerformed
        ClsEEmpleado objEC=new ClsEEmpleado();
        ClsNEmpleado objNC=new ClsNEmpleado();
        if(!txtid.getText().equals(""))
        {
            objEC.setId(Integer.parseInt(txtid.getText()));
            objEC.setUsu(txtdniM.getText());
            objEC.setClave(txtdniM.getText());
            objEC.setEstado_usuario("ACTIVO");
            //objEC.setEstado(1);
            if(objNC.VerificarExisteUsuario(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "El empleado ya tiene una cuenta");
            }
            else
            {
                objNC.MtdRegistrarUsuario(objEC);
                JOptionPane.showMessageDialog(null, "Cuenta Generada");
                mtdlimpiarcajas();

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario");
        }
    }//GEN-LAST:event_btngenerarcuentaActionPerformed

    private void txttelefonoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoMKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){b=1;}

        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txttelefonoMKeyTyped

    private void txtdniMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniMKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){b=1;}

        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txtdniMKeyTyped

    private void txtsueldoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsueldoMKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){b=1;}

        }
        if(b==0){evt.consume();  getToolkit().beep(); }
    }//GEN-LAST:event_txtsueldoMKeyTyped

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        try {
            ClsEEmpleado objEC=new ClsEEmpleado();
            ClsNEmpleado objNC=new ClsNEmpleado();
            int tipousuario =  cboAreaTrb.getSelectedIndex();
            objEC.setId(Integer.parseInt(txtid.getText()));
            objEC.setDni(txtdniM.getText());
            objEC.setCargoempleado(tipousuario);
            objEC.setNombre(txtnombreM.getText());
            objEC.setDireccion(txtdireccionM.getText());
            objEC.setEmail(txtemailM.getText());
            objEC.setTelefono(txttelefonoM.getText());
            File ruta = new File(ruta1);
            try{
                byte[] icono = new byte[(int) ruta.length()];
                InputStream input = new FileInputStream(ruta);
                input.read(icono);
                objEC.setImagen(icono);
            }catch(Exception ex){
                objEC.setImagen(null);
            }
            objEC.setEstado_empleado("ACTIVO");
            objEC.setSueldo(Double.parseDouble(txtsueldoM.getText()));
            int respuesta = JOptionPane.showConfirmDialog(this, "Desea modificar?","Confirmacion"
                ,JOptionPane.YES_NO_OPTION);
            if (respuesta==0)
            {
                if(objNC.MtdModificarempleado(objEC)==true)
                {
                    JOptionPane.showMessageDialog(null, "Datos Guardatos Correctamente");
                    mtdlimpiarcajas();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error datos incompletos");
                }
            }
            else
            {
                mtdlimpiarcajas();
            }
            mtdlistartabla();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnseleccionarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarfotoActionPerformed
        buscarimagen();
    }//GEN-LAST:event_btnseleccionarfotoActionPerformed

    private void btnnuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevo1ActionPerformed
        txtdni.setText("");
        txtnombre.setText("");
        txtdireccion4.setText("");
        txtemail1.setText("");
        txttelefono.setText("");
        txtsueldo.setText("");
        btnregistrar.enable(true);
        btncancelar.enable(true);
    }//GEN-LAST:event_btnnuevo1ActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        ClsEEmpleado objEC=new ClsEEmpleado();
        ClsNEmpleado objNC=new ClsNEmpleado();
        Date date=new Date();
        DateFormat fechaHora=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        int tipousuario =  cbocargo.getSelectedIndex();
        if(!txtdni.getText().equals("")&& !txtdireccion4.equals("") && !txtnombre.getText().equals("")&& !txtemail1.equals("") && !txttelefono.getText().equals("") && !txtsueldo.getText().equals(""))
        {
            objEC.setDni(txtdni.getText());
            objEC.setCargoempleado(tipousuario);
            objEC.setNombre(txtnombre.getText());
            objEC.setDireccion(txtdireccion4.getText());
            objEC.setEmail(txtemail1.getText());
            objEC.setTelefono(txttelefono.getText());
            if(rbtnfemenino.isSelected()==true)
            {
                objEC.setSexo("Femenino");
            }
            else if(rbtnmasculino.isSelected()==true)
            {
                objEC.setSexo("Masculino");
            }
            objEC.setFecha(fechaHora.format(date));
            File ruta = new File(ruta1);
            try{
                byte[] icono = new byte[(int) ruta.length()];
                InputStream input = new FileInputStream(ruta);
                input.read(icono);
                objEC.setImagen(icono);
            }catch(Exception ex){
                objEC.setImagen(null);
            }
            objEC.setEstado_empleado("ACTIVO");
            objEC.setSueldo(Double.parseDouble(txtsueldo.getText()));
            //objEC.setEstado(1);
            if(objNC.VerificarExiste(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "El Nro de DNI ya existe");
            }
            else
            {
                objNC.MtdRegistrarEmpleado(objEC);
                mtdlimpiarcajas();

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Existen campos vacios");
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        mtdlimpiarcajas();
        btnregistrar.enable(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnbuscardniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscardniMouseExited
        btnbuscardni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_btnbuscardniMouseExited

    private void btnbuscardniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscardniMouseClicked

    }//GEN-LAST:event_btnbuscardniMouseClicked

    private void btnbuscardniMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscardniMouseMoved
        btnbuscardni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_btnbuscardniMouseMoved

    private void btnsuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuspenderActionPerformed
        ClsEEmpleado objEC=new ClsEEmpleado();
        ClsNEmpleado objNC=new ClsNEmpleado();
        if(!txtid.getText().equals(""))
        {
            objEC.setId(Integer.parseInt(txtid.getText()));
            objEC.setEstado_usuario("INACTIVO");
            if(objNC.Suspender_Empleado(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "Usuario Suspendido ");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error al momento de suspender al usuario ");

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario");
        }
        mtdlistartabla();
    }//GEN-LAST:event_btnsuspenderActionPerformed

    private void btnactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactivarActionPerformed
        ClsEEmpleado objEC=new ClsEEmpleado();
        ClsNEmpleado objNC=new ClsNEmpleado();
        if(!txtid.getText().equals(""))
        {
            objEC.setId(Integer.parseInt(txtid.getText()));
            objEC.setEstado_usuario("ACTIVO");
            if(objNC.Activar_Empleado(objEC)==true)
            {
                JOptionPane.showMessageDialog(null, "Usuario Activado ");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error al momento de Activar al usuario ");

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario");
        }
        mtdlistartabla();
    }//GEN-LAST:event_btnactivarActionPerformed

    private void buscarimagen()
    {
        JFileChooser carpeta=new JFileChooser();
        carpeta.setDialogTitle("Selecionar Foto de perfil");
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        carpeta.setFileFilter(fil);
        File rutacarpeta= new File("");
        carpeta.setCurrentDirectory(rutacarpeta);
        int ventana=carpeta.showOpenDialog(carpeta);
        if(ventana==JFileChooser.APPROVE_OPTION)
        {
            ruta=carpeta.getSelectedFile();
            IMG=getToolkit().getImage(String.valueOf(String.valueOf(ruta)));
            ruta1=String.valueOf(ruta);
            IMG=IMG.getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT);
            lblimagen.setIcon(new ImageIcon(IMG));
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactivar;
    private javax.swing.JButton btnbloquearcuenta;
    private javax.swing.JLabel btnbuscardni;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btndesbloquearcuenta;
    private javax.swing.JButton btngenerarcuenta;
    private javax.swing.ButtonGroup btngpsexo;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo1;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private rojerusan.RSButtonIconD btnseleccionarfoto;
    private javax.swing.JButton btnsuspender;
    private javax.swing.JComboBox cboAreaTrb;
    private javax.swing.JComboBox<String> cbocargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JRadioButton rbtnfemenino;
    private javax.swing.JRadioButton rbtnmasculino;
    private javax.swing.JTable tblRegistrosEmpl;
    private rojeru_san.RSMTextFull txtdireccion4;
    private javax.swing.JTextField txtdireccionM;
    private rojeru_san.RSMTextFull txtdni;
    private javax.swing.JTextField txtdniM;
    private rojeru_san.RSMTextFull txtemail1;
    private javax.swing.JTextField txtemailM;
    private javax.swing.JTextField txtid;
    private rojeru_san.RSMTextFull txtnombre;
    private javax.swing.JTextField txtnombreM;
    private rojeru_san.RSMTextFull txtsueldo;
    private javax.swing.JTextField txtsueldoM;
    private rojeru_san.RSMTextFull txttelefono;
    private javax.swing.JTextField txttelefonoM;
    // End of variables declaration//GEN-END:variables

    private void mtdlimpiarcajas() {
        txtdni.setText("");
        txtnombre.setText("");
        txtdireccion4.setText("");
        txtemail1.setText("");
        txttelefono.setText("");
        txtsueldo.setText("");
    }


    private void mtdmostrarcombo() {
        ArrayList<String> lista=new ArrayList<String>();
        lista= ClsConsulta.llenarcombo();
        for(int i=0;i<lista.size();i++)
        {
            cbocargo.addItem(lista.get(i));
            cboAreaTrb.addItem(lista.get(i));
        }
    }
    private void mtdindicestabla()
    {
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("CARGO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("EMAIL");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("SEXO");
        modelo.addColumn("ESTADO");
        modelo.addColumn("SUELDO");
        modelo.addColumn("FECHA INICIO");
        this.tblRegistrosEmpl.setModel(modelo);
        tblRegistrosEmpl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumnModel columnModel = tblRegistrosEmpl.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(120);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(300);
        columnModel.getColumn(4).setPreferredWidth(300);
        columnModel.getColumn(5).setPreferredWidth(200);
        columnModel.getColumn(6).setPreferredWidth(100);
        columnModel.getColumn(7).setPreferredWidth(100);
        columnModel.getColumn(8).setPreferredWidth(100);
        columnModel.getColumn(9).setPreferredWidth(80);
        columnModel.getColumn(10).setPreferredWidth(150);
    }
    private void mtdlistartabla() {
        mtdindicestabla();
        ClsNEmpleado objNC=new ClsNEmpleado();
        String[] datos=new String[11];
        for(ClsEEmpleado objE: objNC.MtdListar())
        {
            datos[0]=String.valueOf(objE.getId());
            datos[1]=objE.getDni();
            datos[2]=objE.getCargo_empleadonombre();
            datos[3]=objE.getNombre();
            datos[4]=objE.getDireccion();
            datos[5]=objE.getEmail();
            datos[6]=objE.getTelefono();
            datos[7]=objE.getSexo();
            datos[8]=objE.getEstado_empleado();
            datos[9]=String.valueOf(objE.getSueldo());
            datos[10]=objE.getFecha();
            modelo.addRow(datos);

        }
        this.tblRegistrosEmpl.setModel(modelo);
        
        
    }

    private void mtdbotones() {
        btnregistrar.enable(false);
        btncancelar.enable(false);
    }

    private void mtdmostrarimagen() {
        
    }
    
    
}
